### ISSUE TITLE
N: BN API Call and Excel workflow

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#100]
Goal: By end of sprint have solution that helps GRU with their QAQC process of new building permits

Work on second week of sprint

Potential solution:
Expand Geosupport API call to include BN and develop Excel workflow where records will be run against BN PAD, then rejects will be run through BN TPAD and the ones that are successful are the records that are outputted.   This is a weekly task for GRU, so solution must be something that is easily reproducible and maintainable.

Work with Dan and Jason

**Comment by SPTKL** [comment]
- observation: we have to work with `.xlsx` format workbooks instead of `xls` workbooks (which throws a lot of errors)

**Comment by AmandaDoyle** [comment]
Delivered spreadsheet to Dan and Jason.  Need to continue to workshop it with them
