### ISSUE TITLE
O: Implement Geocoding for QECW data with HEIP

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#104]
Goal: By end of sprint have workflow established with HEIP for geocoding QCEW data using Python, Geosupport, and R installed on PC

@SPTKL will 
1) complete training to view QCEW data
2) get scripts setup for HEIP so that they can geocode independently

**Comment by SPTKL** [comment]
updates: 
- completed confidentiality training 
- waiting to get access to the encrypted drive

**Comment by SPTKL** [comment]
Updates: 
- got access to the encrypted drive folder
- developing a draft workflow

**Comment by AmandaDoyle** [comment]
Project overflows into work with Population and Rodrigo

**Comment by AmandaDoyle** [comment]
Setup is complete.  Waiting on HEIP to provide research
