### ISSUE TITLE
N: Develop materials for data users group meeting

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#105]
Goal: By end of week 1 deliver materials for data users group meeting to Lynn

Materials needs:
1) Instructions on how to geocode via API in Excel (can be google doc, blog, or github page)
2) Instructions on how to geocode using Python, GeoSupport, and R on PC  (can be google doc, blog, or github page)
3) Deck on explaining / demonstrating how to geocode via API in Excel and using Python, GeoSupport, and R on PC (Google slides)
4) Slides on plans for PLUTO (same as Hassan meeting)(Google slides)
5) Slide on changes to FacDB (Google slides)

- [x] @SPTKL Draft materials 1, 2, and 3 as described above (workshop with team as needed)
- [x] Deliver to @baolingz and @bendnorman for review by Wednesday
- [x] Deliver to @AmandaDoyle by Friday for final review
- [x] Deliver to @lseirup by Monday

**Comment by SPTKL** [comment]
Slide deck: https://docs.google.com/presentation/d/155rVmsrAaJsPOQ0xHTKivJEe0RAPbl14N6dIIH7w4RA/edit?usp=sharing
Blog on Python-geosupport draft: 
https://medium.com/@sptkl/geosupport-%EF%B8%8Fpython-a094a2d30fbe
Blog on geosupport-api: 
https://medium.com/@sptkl/geosupport-%EF%B8%8F-api-987554581a09
Blog on geocoding using Excel: 
https://medium.com/@sptkl/geosupport-in-excel-75e98606516b

**Comment by AmandaDoyle** [comment]
@SPTKL 
Awesome first drafts for the three blog series on geocoding
I copied the blogs and made comments / suggested edits in this Google Doc
https://docs.google.com/document/d/1JXA4XRy6qQYhiUAAhKfFvbX87Uu4YxDk1YMl9Jh-rCo/edit?usp=sharing
Things to be mindful of are consistency is case and tense

I also added slides to the deck.

Can you do a final round of edits on Monday and we can send it to Lynn for review on Tuesday?
