### ISSUE TITLE
N: DCM Distribution Script

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#112]
Script necessary for pulling DCM Feature Classes from sde@GISPROD and distributing to appropriate locations:
- [x] Shapefiles in M:\GIS\BytesProduction\ (remove all fields except the following)
    - DCM: Boro_nm, Feature_type, type, Source, Jurisdiction, Ownership_status
    - DCM_SCL: Streetwidth, Official_street_name, Roadway_type, Boro_name, feature_status
    - DCM_NYMI: app_num, Status, Effective, borocode, altmappdf, chg_type, scanned, project_name, filed_status
- [ ] Layers and xmls in M:\GIS\DATA\City Map

**Comment by croswell81** [comment]
7/8: Based on meeting w/ TRD & Labs on 7/3, schema will be changing and this script will have to be updated. Metadata needs to be reviewed and updated.
