### ISSUE TITLE
O: Publish PLUTO

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#124]
Goal: Publish PLUTO by the end of the sprint. Deliver to Adrian by end of week 1

- [x]   Load in latest zoning data (sprint O)
- [x]   Correct Geosupport fields
- [x]   Build PLUTO
- [x]   QAQC PLUTO
- [ ]   Deliver PLUTO to @aferrar for Esrify it by end of week 1

**Comment by AmandaDoyle** [comment]
After initial review need to answer / investigate

- [ ] Why does the Ext field have so many additional values?

- [ ] Need to investigate the drop in total LotArea

- [ ] In addition to the Geosupport formatting issues mentioned below, I’m seeing CD and SchoolDist with blank values (~5% of records in test sample)

- [ ] BBLs with addresses without a house number are now null – this is fine, as long as that’s what PTS is returning (~19,000 records)

- [ ] Need to delete field ExemptLand

- [ ] Unexpected changes in NumBldgs, e.g. BBL 2056410120 - GOAT has 5 buildings, PLUTO is showing 14

- [ ] Geometries are shifted ~ 3 ft. Possibly caused by undefined projection on shapefile given to Adrian?

**Comment by AmandaDoyle** [comment]
Re: Why does the Ext field have so many additional values?
PTS now has 'N' as value, instead of NULL
see issue https://github.com/NYCPlanning/db-pluto/issues/49

<img width="260" alt="Screen Shot 2019-07-22 at 2 27 34 PM" src="https://user-images.githubusercontent.com/5611960/61655621-ec37f580-ac8c-11e9-885b-4ba80c325eb3.png">

**Comment by AmandaDoyle** [comment]
Re  Need to investigate the drop in total LotArea
`land_area` values are 0 in PTS 
Per the field mapping spreadsheet LAND_AREA > AV-LAND-AREA, which is If not 0, Total Land Area 
So what should it be if it is zero?

query 
`SELECT a.bbl, a.lotarea::double precision, b.lotarea::double precision, (a.lotarea::double precision - b.lotarea::double precision)::double precision AS diff
FROM pluto a
INNER JOIN dcp_pluto b
ON a.bbl::text=b.bbl::text
WHERE (a.lotarea::double precision - b.lotarea::double precision)::double precision < -50
ORDER BY diff ASC`

<img width="463" alt="Screen Shot 2019-07-22 at 2 46 38 PM" src="https://user-images.githubusercontent.com/5611960/61656819-90bb3700-ac8f-11e9-8b6d-ac2842ddb2ff.png">

**Comment by SPTKL** [comment]
it's strange because if we run function BL, there are 5 structures, if we run 1B with the address there would be 14

http://a030-goat.nyc.gov/goat/FunctionBL?block=05641&lot=0090&borough=2

http://a030-goat.nyc.gov/goat/Function1B?borough=2&street=CITY%20ISLAND%20AVENUE&address=130

and for some reason, when running 1B, the returned bbl is 2056410090 (instead of 2056410120)

**Comment by SPTKL** [comment]
- there are 32841 records in PTS that have input house number missing, 
- and there are 35751 records didn't get a communitySchoolDistrict (majority of them explained by missing house number), 
- about 2996 records have input house number and input street name but are address number out of range, therefore all spatial attributes are left as null

NULL counts for each spatial attributes are pretty consistent
![image](https://user-images.githubusercontent.com/13207770/61722980-42627280-ad39-11e9-9edc-f32873620f4d.png)
![image](https://user-images.githubusercontent.com/13207770/61723030-5908c980-ad39-11e9-848e-e6bc394f09d7.png)

```
SELECT 
SUM(CASE WHEN billingbbl IS NULL THEN 1 ELSE 0 END) AS billingbbl,
SUM(CASE WHEN communityDistrict IS NULL THEN 1 ELSE 0 END) AS communityDistrict,
SUM(CASE WHEN censusTract2010 = '000000' THEN 1 ELSE 0 END) AS censusTract2010,
SUM(CASE WHEN censusBlock2010 IS NULL THEN 1 ELSE 0 END) AS censusBlock2010,
SUM(CASE WHEN communitySchoolDistrict IS NULL THEN 1 ELSE 0 END) AS communitySchoolDistrict,
SUM(CASE WHEN cityCouncilDistrict IS NULL THEN 1 ELSE 0 END) AS cityCouncilDistrict,
SUM(CASE WHEN zipCode IS NULL THEN 1 ELSE 0 END) AS zipCode,
SUM(CASE WHEN fireCompanyNumber IS NULL THEN 1 ELSE 0 END) AS fireCompanyNumber,
SUM(CASE WHEN policePrecinct IS NULL THEN 1 ELSE 0 END) AS policePrecinct,
SUM(CASE WHEN healthCenterDistrict IS NULL THEN 1 ELSE 0 END) AS healthCenterDistrict,
SUM(CASE WHEN healthArea IS NULL THEN 1 ELSE 0 END) AS healthArea,
SUM(CASE WHEN sanitationDistrict IS NULL THEN 1 ELSE 0 END) AS sanitationDistrict,
SUM(CASE WHEN sanitationCollectionScheduling IS NULL THEN 1 ELSE 0 END) AS sanitationCollectionScheduling,
SUM(CASE WHEN boePreferredStreetName IS NULL THEN 1 ELSE 0 END) AS boePreferredStreetName,
SUM(CASE WHEN numberOfExistingStructures IS NULL THEN 1 ELSE 0 END) AS numberOfExistingStructures,
SUM(CASE WHEN taxMapNumberSectionAndVolume IS NULL THEN 1 ELSE 0 END) AS taxMapNumberSectionAndVolume,
SUM(CASE WHEN sanbornMapIdentifier IS NULL THEN 1 ELSE 0 END) AS sanbornMapIdentifier,
SUM(CASE WHEN longitude IS NULL THEN 1 ELSE 0 END) AS longitude,
SUM(CASE WHEN latitude IS NULL THEN 1 ELSE 0 END) AS latitude
FROM pluto_input_geocodes;
```

**Comment by AmandaDoyle** [comment]
Generation of PLUTO revealed that there are skelton records for condo billing lots in PTS and that PTS and CAMA are out of sync

Cannot regenerate and publish PLUTO until data issues are resolved by DOF
