### ISSUE TITLE
O: Set up product repos

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#128]
Pushing GIS Team scripts to independent github repos.
- [x] POPS
- [x] E-Designations
- [x] FTP Upload
- [x] MIH Generation / Distribution
- [x] Open Data Building Footprints
- [x] Open Data LPC
- [x] MapPLUTO Archive
- [x] MapPLUTO ESRI Conversion
- [x] LION Archive
- [ ] Carto Upload
- [ ] DCM

**Comment by croswell81** [comment]
@aferrar  you can close this issue. move DCM script to #111 and create new issue for CARTO script for next sprint (P)
