### ISSUE TITLE
P: Open Data - WPAAs

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#139]
- [ ] WPAAs: prepare pages for Bytes and Open Data
  - [ ] package data for sharing (Bytes Production)
  - [ ] add to SDE PROD and create/source layer files on M drive
  - [ ] prepare pages for Bytes and Open Data

**Comment by aferrar** [comment]
08/08/2019
Waiting on field descriptions from Chris Wassif before packaging of data can take place.
