### ISSUE TITLE
R: R&D - Deploying several versions of Geosupport for API

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#167]

**Comment by SPTKL** [comment]
https://github.com/NYCPlanning/api-multi-geosupport 
- first phase complete, using docker compose, we have a version that runs locally
versions included: 18[a,b,c,d], 19[a,b,b2]
- next step: 
  - deployment on a server
  - figure out how to implement ssl

**Comment by AmandaDoyle** [comment]
Closing because initial R&D is complete.  We now need to do follow through and discuss with Hassan to determine how to deploy this
