### ISSUE TITLE
M: Implement Geocoding for HEIP for QCEW

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#20]

**Comment by AmandaDoyle** [comment]
HEIP needs data by August 1, but it would be great to build a tool for them to use so that they can do any geocoding themselves

**Comment by AmandaDoyle** [comment]
@SPTKL is going to work with transportation and HEIP to get geocoding solution deployed locally on their PCs to meet their needs

**Comment by AmandaDoyle** [comment]
@SPTKL Met with HEIP to introduce geocoding solution.

PCNS said that we cannot use Docker, so PCNS is going to install necessary software (Python, R, and Geosupport) on machines.
