### ISSUE TITLE
S: Test dockerized production environments

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#209]
- [x] @aferrar run ZTLDB (QC should compare to version produced on August 30)
- [x] @aferrar run FacDB
- [ ] @lseirup run ZTLDB

**Comment by aferrar** [comment]
09/10/2019
*ZTLDB:* Documentation provided was very helpful and the general workflow was seamless with no issues. Added documentation to M: drive in a location where we keep docs for other tools we use often so we will have access in the future.

*FacDB:* Need documentation for this whenever it is readily available to test running on local machines.

**Comment by AmandaDoyle** [comment]
Closing
@SPTKL @baolingz Will incorporate feedback from @aferrar in next iteration
