### ISSUE TITLE
S: Expand QAQC procedures for productionalized datasets

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#213]
Goal: Tighten up QAQC reports / process for ZTLDB and FacDB

- [x] @lseirup to provide list of QAQC checks she'd like added to ZTLDB
- [x] Expand Jupyter notebook for ZTLDB QAQC
- [ ] Have Lynn run ZTLDB QAQC notebook

- [ ] @lseirup run current FacDB QAQC notebook
- [ ] @lseirup provide list of QAQC checks she'd like added to FacDB
- [ ] Have Lynn run QAQC notebook

**Comment by SPTKL** [comment]
+ ZTLDB qaqc notebooks are ready to go

**Comment by AmandaDoyle** [comment]
Successfully created ZTLDB QAQC notebook.  Closing and moving FacDB to a different issues
