### ISSUE TITLE
Pseudo lots

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#22]
- [x] Update dataset (GRU) #97
- [ ] Set up versioned editing in SDE for future updates (GIS)
- [ ] Release on Bytes/Open Data (GIS)
- [ ] Incorporate into PLUTO (DE)
- [ ] Remove from DOF's DTM release
- [ ] Update xy coordinates in Geosupport (Geo)

**Comment by lseirup** [comment]
- [ ] Update dataset (GRU)
- [ ] Release on Bytes/Open Data (GIS)
- [ ] Incorporate into PLUTO (ED)
- [ ] Remove from DOF website

**Comment by TomMCosta** [comment]
Above DOF task should be "Remove from DOF's DTM release"

**Comment by TomMCosta** [comment]
Dan completed the data update for PAD and the drawing of lot polygons in the layer.

**Comment by croswell81** [comment]
@lseirup Is this still relevant? Do we want to pick this up now that we have some time to focus on these types of issues?

**Comment by TomMCosta** [comment]
Sounds good to me

TOM COSTA, AICP
MANAGER OF GEOGRAPHIC RESEARCH • ENTERPRISE DATA MANAGEMENT

NYC DEPARTMENT OF CITY PLANNING
120 BROADWAY, 31st FLOOR • NEW YORK, NY 10271
212.720.3441  tcosta@planning.nyc.gov<mailto:tcosta@planning.nyc.gov>

Follow us on Twitter @NYCPlanning<http://www.twitter.com/nycplanning>
http://www.nyc.gov/planning

**Comment by AmandaDoyle** [comment]
This is complete.  Pseudo lots were published in Q3 2022
