### ISSUE TITLE
W: CPDB - plan to update database

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#225]
When capital commitment plan is released, collect input data, and produce database.  Amanda will do this during week 2

**Comment by AmandaDoyle** [comment]
Capital commitment plan was released
https://www1.nyc.gov/site/omb/publications/fy20-accp.page

**Comment by AmandaDoyle** [comment]
Loaded FMS into FTP

**Comment by SPTKL** [comment]
- initial dockerization is complete
 - still need dcp_trafficanalysiszones
 - dcp_agencyverfied files

**Comment by AmandaDoyle** [comment]
Delivered updated dataset to capital planning on Nov 15
