### ISSUE TITLE
K: FacDB

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#24]
- [x] Continue with pipeline
- [ ] Final processing script (with deduplication)
- [x] Get data to Labs for sprint L

**Comment by SPTKL** [comment]
Current progress: 
- `36` datasets loaded to S3
- `27` confirmed datasets transformed, geocoded and loaded to postgres database
- created postgres function to load individual source data to main table
- delivered a subset of main table to labs for the capital planning platform development
