### ISSUE TITLE
V: FacDB - improve documentation for running in docker

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#242]
@aferrar feedback

FacDB: Need documentation for this whenever it is readily available to test running on local machines.

09/16/2019
FacDB: Ran associated shell scripts for db-facilities-temp. Only errors encountered were related to containers that were already running or that were not initialized correctly, but was fixed easily when consulting Baiyue. Would be helpful if a portion of the documentation covered troubleshooting issues (e.g. "If you receive the error Error response from daemon: Conflict. The name "container name" is already in use by container "container id". you must run the following commands: docker container kill facdb fdb api-geosupport, then docker container prune, then re-run sh 00_initialize.sh.

Additionally (minor critique) the first step of the README in the db-facilities-temp repo is a bit confusing as it is not entirely clear that you don't have to run the code snippets provided (docker run -itd --name=facdb..., docker run -itd --name=fdb..., docker run -itd -p 5000:5000 sptkl/api-geosupport...) if you've already run sh 00_initialize.sh.

**Comment by AmandaDoyle** [comment]
Moving over to U sprint.  AF is going to update documentation

**Comment by SPTKL** [comment]
facdb is completely rebuilt, the build process is now significantly faster and easier
