### ISSUE TITLE
W: PLUTO - produce and publish 19v2 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#247]
- [x] Load datasets from source dataset list and review input data
- [x] Update pluto input research file
- [x] Build PLUTO
- [x] Review QAQC reports and flag any anomalies (@SPTKL @baolingz @aferrar review together)
- [x] Deliver deliverables to @aferrar  and then to Lynn

**Comment by SPTKL** [comment]
- a successful reran was delivered to Adrian and Lynn Thursday morning
- awaiting review

**Comment by AmandaDoyle** [comment]
Delivered 19v2 w/ and w/o corrections to Lynn today

Awaiting sign off so that it can be published.  Some PLUTO work may carry over into sprint X
