### ISSUE TITLE
D: Buildings composite

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#248]
Generate and publish buildings composite dataset

**Comment by AmandaDoyle** [comment]
- [ ] team to conduct a code review and give feedback

**Comment by AmandaDoyle** [comment]
- [ ] Transition building composite dataset to DE

**Comment by mgraber** [comment]
Current repo for this issue: https://github.com/NYCPlanning/db-buildings-composite

**Comment by mgraber** [comment]
- [ ] Refactor PAD address string processing

- [ ] Refactor Melissa address string processing, with special considerations for efficient memory usage

- [ ] Merge PLUTO with footprints on BBL to get lot-level info (SQL)

- [ ] Incorporate PAD, Melissa, and OEM address strings

- [ ] Move workflow out of geosupport docker containers

**Comment by mgraber** [comment]
**Transition to DE**
- [x] Refactor PAD address string processing

- [ ] Refactor Melissa address string processing, with special considerations for efficient memory usage

- [ ] Merge PLUTO with footprints on BBL to get lot-level info (SQL)

- [ ] Incorporate PAD, Melissa, and OEM address strings

- [ ] Move workflow out of geosupport docker containers

**Comment by AmandaDoyle** [comment]
Carrying over into E because it we need to finalize dataset and work with GIS to create schema
