### ISSUE TITLE
W: Test dockerized production environments

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#269]
@aferrar Built ZTLDB through Jupyter Notebook and ran/tested QA/QC. Is available for review by Lynn
- [ ] @lseirup run ZTLDB

References #209 & #234

**Comment by aferrar** [comment]
10/31/2019
Discussed the possibility of Rodrigo or another GRU member getting some experience running the ZTLDB for better coverage of users capable of generating the data product.

**Comment by croswell81** [comment]
Closed - this work is being passed on to GRU
