### ISSUE TITLE
A: ACS / Pop Fact finder data update

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#278]
Data is scheduled to be released on December 19

**Comment by SPTKL** [comment]
replication complete, waiting for population to give instructions on generating 2014-2018 version.

**Comment by SPTKL** [comment]
+ 2014-2018 updates completed
+ doing last minute QAQC with populations

**Comment by AmandaDoyle** [comment]
@SPTKL made significant progress on this.  He's going to continue to work on this with population team early on in strint now

Current status is: around 10 records that have differences in median moe calculations, but they are in parks
