### ISSUE TITLE
W: Create Automated Monthly Email for Zoning GIS file updates

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#287]
We need to create an automated monthly email that is sent to the Zoning Division (Paul Power) to request if any zoning map or text amendments were adopted that would produce changes to the following GIS files:

-MIH (Appendix F)
-Inclusionary Housing (VIH)
-Transit Zones
-FRESH
-Lower Density Growth Management Areas (LDGMA)
-Waterfront Access Plan (WAP)
-Designated Areas in Manufacturing Districts (Appendix J)
-DCP Initiated Rezonings

Should also check w/ Zoning Division to see if there are other mapped areas within the ZR that should 
become new datasets

Tasks:
- [x] Write script to automatically request information from Zoning Division (Paul Power)
- [x] Schedule script to be run at a pre-determined time.

**Comment by aferrar** [comment]
**11/6/2019**
Created automated email for Zoning Division (Paul Power). Sent a test/example of it to GISTeam and Matt's email for review when ready. Still needs to be scheduled for a particular time (I believe the frequency is monthly but will double check).

**Comment by aferrar** [comment]
**11/13/2019**
Script is complete and has been scheduled for the last day of each month @ 9am. Need to verify that this is an adequate scheduling time before closing issue. Will update with new comment if the scheduling frequency changes.

**Comment by aferrar** [comment]
**11/13/2019**
Scheduling changed to the 24th @ 9am. Closing issue as this has been scheduled and is ready to run on 11/24/2019.
