### ISSUE TITLE
X: Automate Open Data and MMR reporting

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#288]
Write a script to automatically generate the emails we send to NYC Open Data team and automatically generates the excel spreadsheets we send to Planning Coordination.

- [x] Generate new sheet for data sets that have a BytesProduction date older than the NYC Open Data report Last Posting Date
- [x] Copy and send new sheet in an email addressed to Open Data team
- [x] Populate MMR sheet with information from the first step's newly generated sheet
- [x] Copy and send new MMR sheet in an email addressed to Planning Coordination team

**Comment by aferrar** [comment]
**11/18/2019**
Moved to sprint X. Didn't have time to complete in W.

**Comment by croswell81** [comment]
@aferrar is this please completed? Please close if yes.
