### ISSUE TITLE
X: GRU Geocoding vs Atomic Polygon join QAQC project

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#296]
See what atomic polygon is returned by GeoSupport, verses what atomic polygon is address point is spatially joined to

This will help solve the census block issue

Work with GRU

**Comment by SPTKL** [comment]
need to load atomic polygon to recipe database
https://data.cityofnewyork.us/City-Government/Atomic-Polygons/djze-f4qi

**Comment by baolingz** [comment]
Done, the outputs is here: https://github.com/NYCPlanning/db-atomicpolygon-qaqc/tree/master/output

**Comment by AmandaDoyle** [comment]
@baolingz delivered output of analysis to Rodrigo
closing
