### ISSUE TITLE
M: Housing database enhancements

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#30]
- [x] Decide on enhancements we'll make during this sprint on Monday with capital planning and HEIP
- [x] Execute issues
- [ ] Dockerize DB

**Comment by AmandaDoyle** [comment]
Identified 9 priority issues
Executed on the issues
Need to confirm that issue 61 and 24 are implemented correctly
Have 2 outstanding issues
Mostly dockerized DB build.  Issue is that datasets are too large that they crash the server and values are coming in as 'None' instead of NULL
