### ISSUE TITLE
B: QECW - geocoding

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#305]
Potential project
Improving geocoding logic based on their research, and integrating HED corrected addresses

Dependent on HED receiving QECW data

**Comment by AmandaDoyle** [comment]
@SPTKL What's the status of this?  If it's done or no future action is to be taken by EDM can you write a brief description of any work (if there was any) and close the issue?

**Comment by SPTKL** [comment]
HED never followed up with us, so this is on hold, no future action needed at this momment

**Comment by AmandaDoyle** [comment]
DE received updated QCEW data from ERD.  DE delivered updated geocoded data to ERD and made some high impact enhancements
