### ISSUE TITLE
C: CEQR Air - finalize datasets

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#313]
- [x] Meet with Rodrigo and decide on best approach for correcting addresses for permit records that did not get geocoded
- [ ] Correct addresses and incorporate corrections 
- [ ] Make corrections to Garages or Atypical roadways as needed (dependent on EARD response)
- [x] Apply desired schema to CEQR Air datasets for M drive (DE will update field names, but GIS will need to update field aliases and hide fields)
https://docs.google.com/spreadsheets/d/1TWZid5kx-OCvZolgwXBXxIDA03Y5HV6DRx3dVXX0UhE/edit?usp=sharing

**Comment by AmandaDoyle** [comment]
Moving to on hold because we will not move forward until we hear back from EARD

**Comment by AmandaDoyle** [comment]
For DEP CATS permits
Filter = drop the following records
purged the following permits (permits that are not required for air quality analysis):

All Cancelled permits
All G-prefix permits
All C-prefix + Registration (including Registration, Boiler Registration II, and Registration Inspection)
All CA-Prefix + Work Permit + Expired permits

In the datasets attached, with the filters applied, there are remaining 20,394 permits. As shown in the GIS Attribute Table, there are 36,084.  **Why is there this inconsistency?**
[Archive 3.zip](https://github.com/NYCPlanning/edm-overview/files/4056475/Archive.3.zip)

See Google Sheet for notes on columns to show, naming, etc. - GIS to discuss the implications of hiding columns with EARD

EARD wil continue to give feedback on the datasets via issues

**Comment by baolingz** [comment]
After applying the following filter on the `dep_cats_permits` on `recipe`, we got 20555 records remained.
```
SELECT COUNT(*) FROM dep_cats_permits.latest
WHERE TRIM(status) != 'CANCELLED'
AND LEFT(applicationid, 1) != 'G'
AND (LEFT(applicationid, 1) != 'C' OR (requesttype != 'REGISTRATION' AND requesttype != 'REGISTRATION INSPECTION' AND requesttype != 'BOILER REGISTRATION II'))
AND (LEFT(applicationid, 2) != 'CA' OR requesttype != 'WORK PERMIT' OR TRIM(status) != 'EXPIRED')
;
```

**Comment by aferrar** [comment]
**1/30/20**
Applied aliases to all fields in all data sets. Matt is committed to filling out our suggestions for which fields to hide/display.

**Comment by baolingz** [comment]
@aferrar I updated DEP CATS permits (applied filter) and NYSDEC Title V Facil Permits (update the URL to access pdf) according to EARD's last-minute requests. You can find the latest shapefiles and their corresponding geo_rejects.csv in [here](https://drive.google.com/open?id=1-3EKef1z98BvcC6pSwx1Q9zKnIL9658i). Could you please update the version in SDE as well? Thank you very much!

**Comment by AmandaDoyle** [comment]
Once data in SDE is we can close out the issue

**Comment by aferrar** [comment]
**2/11/2020**

Uploaded revised data to SDE and re-sourced layer files.
