### ISSUE TITLE
H: SDE Upgrade to ArcGIS 10.4 

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#317]
###

- [x] **Complete and submit change management form**

**SDE Upgrade and other "GIS To Do's" for 2020:** - also see #324
- [x] Upgrade remaining geodatabases to 10.4 (confirm) 
    - [x] confirm w/ Hernan back up
    - [x] schedule notification to GIS users when SDE will be down

- [x] Remove orphaned tables that prohibit the ability to view locks on 10.6 (after SDE upgrade to 10.4)

See issue #109 and #126 for other completed ESRI upgrade items

**Comment by aferrar** [comment]
Adding potential resources for improving ArcGIS performance for when we upgrade and begin building out the processes for maintaining performane:

* [How To: Increase performance to make ArcMap start and run faster](https://support.esri.com/en/technical-article/000008878)
* [How To: Improve performance working in ArcMap and ArcCatalog](https://support.esri.com/en/technical-article/000010674)

**Comment by aferrar** [comment]
**1/23/2020**

Update - Currently waiting to fill out form required for any modifications to back-end infrastructure. Cannot proceed with upgrade to SDEs without this allowance and a date of last back-up of the data from Hernan.

**Comment by croswell81** [comment]
2/24/20: Submitted Change Management form for meeting on Monday, 3/2/20. If approved, plan on conducting upgrade on Thursday, 3/5/20

**Comment by aferrar** [comment]
Will be pushed back as a result of covid response. Will update with tentative upgrade date when available.

**Comment by croswell81** [comment]
**3/16/20:** Due to prep for remote working this was pushed from 3/5/20 to 3/23/20. This will most likely be suspended indefinitely until the COVID-19 situation is stable.

**Comment by croswell81** [comment]
Scheduled to run 4/9/20 (dependent on successful back up of GIS Archive)

Removed bullet items related to compression and create indices since they are covered in #324.
