### ISSUE TITLE
MIH Enhanced Dataset

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#323]
Executive Office (Taylor) maintains an excel spreadsheet that contains ZAP info related to status, milestones and unit counts. Primary use cases include; track projects in pipeline, public review and post-ULURP; communications tracker; and Unit Summary reporting. Mostly for internal purposes with some reporting to HPD and City Hall.

EDM needs to streamline production of output products.
-Pull data from ZAP (either by views - directly from CRM or via Labs ZAP API)
-Potential to add/combine with GIS shapefile produced montly

Current data procedures:
-copy data from ZAP data pulls (3 views)
-ZAP Project ID is used as unique ID
-data/numbers have to be manually reviewed for quality control
-MIH Boro liaison's help in vetting

**Comment by croswell81** [comment]
1/16/20: Begin initial steps to see what can be done without a ZAP data pipeline starting in Sprint D

**Comment by aferrar** [comment]
Closed due to no longer being needed.
