### ISSUE TITLE
D: GRU QAQC project

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#353]
Data engineering to collaborate with GRU to do a similar project to the atomic polygon project

**Comment by AmandaDoyle** [comment]
1) Building off of atomic polygon project
Run address point addresses through 1A and report any record that fails or returns a warning

2) Run DoITT footprints through BN with TPAD extended and output records that got a hit in TPAD or have a 0 / million BIN

**Comment by AmandaDoyle** [comment]
3. Run DOB developments database output records that have a certificate of occupancy through GeoSupport and output records to GRU that are still in TPAD

**Comment by AmandaDoyle** [comment]
Ann built workflows in B
In D we'll transistion workflows to DE

**Comment by mgraber** [comment]
> 1. Building off of atomic polygon project
>    Address points that aren't in CSCL
>    Run address point addresses through 1A and report any record that fails or returns a warning
> 2. Run DoITT footprints through BN with TPAD extended and output records that got a hit in TPAD or have a 0 / million BIN

The address point check should use function AP.

**Comment by mgraber** [comment]
For current progress on this issue, see: https://github.com/NYCPlanning/db-gru-qaqc

**Comment by AmandaDoyle** [comment]
Also, during this time @baolingz was working to finalize the atomic polygon analysis.  She send Rodrigo an output that was sign off on last week.

**Comment by mgraber** [comment]
Progress update:
* TPAD-DOB
     * written with output in EDM as tpad_dob_qaqc
     * waiting on GRU feedback
* TPAD-Footprints
     * written with output in EDM as tpad_footprints_qaqc
     * need to request feedback from GRU
* CSCL-Address Points
     * written with output in EDM as cscl_address_qaqc
     * need to request feedback from GRU
* Atomic Polygons
     * written with output in EDM as atomicpolygon_qaqc
     * Done!

**Comment by AmandaDoyle** [comment]
Add visual representations and summaries of GRU QAQC results

**Comment by AmandaDoyle** [comment]
Closing.
DE successfully transfered repo to GRU.  We'll pick this back up when 1) GRU is ready to run the QAQC checks and we'll take on a supporting role or 2) GRU is ready to finalize other 2 checks
