### ISSUE TITLE
E: CDBG database update

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#358]
Expect data from OMB
On hold until we receive data

**Comment by AmandaDoyle** [comment]
Received data from OMB today
@SPTKL is running the build process now
We can expect to deliver this this sprint

**Comment by SPTKL** [comment]
- ready to deliever to OMB
- waiting for OMB manual corrections

**Comment by AmandaDoyle** [comment]
- [ ] For records that are not assigned a census tract from GeoSupport and have a BBL, join to PLUTO to populate Census Tract field
- [ ] Add CDBG eligibility field

**Comment by SPTKL** [comment]
complete, waiting for OMB corrections file

**Comment by AmandaDoyle** [comment]
- [ ] Incorporate OMB corrections
- [ ] Add columns as requested by OMB using Lynn's normalized schema
- [ ] Join on attributes from CT eligibility table 
- [ ] Deliver to Lynn

**Comment by AmandaDoyle** [comment]
Delivered final output to OMB this week and received final sign off from OMB today
