### ISSUE TITLE
A: Prepare Facilities DB and POPS for Bytes/Open Data

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#364]
- [x] **Facilities Database (csv)** and **Facilities Database (shp)** 
  - [x] Receive raw data from Lynn
    - [x] (confirm the copy of csv on m drive is correct/final (this is copy downloaded from github on 12/16)
  - [x] Convert feature class to shapefile 
    - [x] (confirm w/ Lynn shapefile is OK for open data - this is how it was released previously
  - [x] Move feature class to SDE
  - [x] Process Files - Create zip files (include metadata, readme, dd, etc. for webteam)
  - [x] Update The Guide card
  - [x] Update Bytes (send email to Webteam)
    - [x] confirm w/ Facilities Bytes page is up to date, may need new download icons for dd, readme, etc
  - [x] Update AGOL
  - [x] Update CARTO
  - [x] Update Open Data log and send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log and email Planning Coordination 
-----

- [x] **Privately Owned Public Spaces (POPS)**
  - [x] Receive raw data from Stella/Erick
  - [x] Convert table to shapefile 
  - [x] Move feature class to SDE
  - [x] Process Files - Create zip files (update metadata field descriptions from dd) for webteam
  - [x] Update The Guide card
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Update CARTO
  - [x] Update Open Data log and send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log and email Planning Coordination

**Comment by aferrar** [comment]
**12/30/2019**
Serving as a placeholder / reminder to send out MMR for this and all other datasets when Zoning becomes available.
