### ISSUE TITLE
Geocoding Group Quarters for Capital Planning

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#37]
Waiting to hear back from Mark

**Comment by SPTKL** [comment]
@mqli322  started working on this using google sheet, follow up next week

**Comment by mqli322** [comment]
Was able to get through most of the ~100 failed addresses to narrow down to the 8 that I really really need BBLs for bc they are potentially newly constructed shelters

**Comment by AmandaDoyle** [comment]
@SPTKL going to reach out to confirm this is closed

**Comment by mqli322** [comment]
I still had outstanding questions to Baiyue over email sent a while back

**Comment by AmandaDoyle** [comment]
Going to close this out.  Next sprint @SPTKL shows Capital Planning how to geocode in Excel an that should meet their needs
