### ISSUE TITLE
A: GIS support

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#382]
Creating this issue to keep track of any assistance that is provided by GIS team for other units as these are not typically tracked through the issue system we utilize on ZenHub. Will create new comments for each support item associated with the particular sprint.

**Comment by aferrar** [comment]
**12/30/2019**

Unit: GRU
Contact: Vlad
Problem: Unable to run Districts python arctoolbox script currently located on M: drive and used for outputting formatted districts data sets for webteam to pick up.
Resolution Status: Currently not resolved
Resolution Methods: No clear resolution methods as of yet, but suggested to have additional ArcGIS asset directories added to system PATH by PCNS so that his machine matches the 10.2 remote machine (which CAN successfully run the script). Currently testing copying Python27 folder from remote machine to network for Vlad to pickup.

**Comment by croswell81** [comment]
Unit: Queens
Contact: Joy Resor
Problem: LiDAR 2017 Land Cover layer not sourced properly. 
Resolution Status: Currently Working
Resolution Meth: Recreated layer under OS authentication.
