### ISSUE TITLE
V: DEP Lunch & Learn: DCP’s rest services Prep

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#392]
Silvia Lorenzo of DEP requested a discussion about DCP rest services for a Lunch & Learn event 
-"Ultimately, we’re just trying to encourage people to make more use of existing rest services, and some users aren’t all that aware of the extent (or history) of open data provided by DCP"

Talking points:
-DCP Open data history brief
-AGOL feature services versus what is available on Bytes/Open Data portal
-Adrian Ferrar: coding used to automate our Open Data and AGOL publishing.

**Comment by aferrar** [comment]
Lunch & Learn was cancelled. May be re-scheduled in the future but at this moment not sure when this event will take place. Will re-open this issue if it is determined that the event will proceed.

**Comment by croswell81** [comment]
This has been rescheduled for 5/12/20. I will re-open the issue.

**Comment by croswell81** [comment]
This has been postponed to Fall 2020 (September/October) as DEP does not hold summer lunch and learns.

**Comment by croswell81** [comment]
Tentatively rescheduled for 9/17

**Comment by croswell81** [comment]
Rescheduled for 10/22

**Comment by croswell81** [comment]
**10/21/20**

- Presentation is created
- Sent to Lynn and Silvia (DEP) for feedback
- Run through scheduled for 10/21/20
