### ISSUE TITLE
N: CEQR - develop and agree on standard data table schema

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#40]
Goal: by end of sprint have established running list of standard data table schema in Google sheets so that 1) when developing pipelines DE has framework on how to standardize fields and 2) Labs knows what field names and values to expect when building application

- [x] develop proposed schema with field name, field type, field description, and domain values (if applicable) 
- [ ] present to broader CEQR team and come to agreement

**Comment by baolingz** [comment]
Here is a draft version of CEQR data standard schema:
https://docs.google.com/spreadsheets/d/1Z41fgiU_mi1KltlS783kUZpPcC8Sn7hUxTqhaNxQFg8/edit?usp=sharing
