### ISSUE TITLE
D: PLUTO - update

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#400]

**Comment by SPTKL** [comment]
source data update is complete, waiting on zoningtaxlots #401

**Comment by SPTKL** [comment]
initial run complete
https://github.com/NYCPlanning/db-pluto/tree/20v2

**Comment by AmandaDoyle** [comment]
reran today and delivered QAQC reports for review

**Comment by AmandaDoyle** [comment]
Made available to GIS on Feb 14.  GIS will create shapefile and deliver for final review

**Comment by AmandaDoyle** [comment]
Still waiting on GIS to deliver final shapefile.  DE will deliver a shapefile to review in the interim

**Comment by AmandaDoyle** [comment]
Reran PLUTO using Geosupport 20A to correct number of buildings on condo lots issue
Removed unnecessary fields from csv output
Delivered updated data to GIS to Esrify
Delivered updated QAQC reports for review

**Comment by AmandaDoyle** [comment]
We did not go with the initial output of PLUTO 20v2 because we were not capturing new assessment values
We regenerated in sprint F with new $ fields
