### ISSUE TITLE
D: CSCL training

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#402]
Plan for second half of sprint C

**Comment by AmandaDoyle** [comment]
Starting week of Feb 17th

**Comment by mgraber** [comment]
Will be held:
* Tue Feb 18 2:30-4:30
* Fri Feb 21 2-4
* Tue Feb 25 2-4
* Wed Feb 26 10-12

**Comment by AmandaDoyle** [comment]
completed 2 sessions
