### ISSUE TITLE
Update GIS Page on DCP Commons

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#419]
Update the GIS Page on DCP Commons:
- [x] audit page and remove any out dated items
- [ ] add all user guides that were updated on EDM page on The Guide (see #322)

**Comment by aferrar** [comment]
Still working on this but just adding some potential resource links for replacing what is currently available on DCP Commons - GIS section:

**Potential items for Sidebar**
- [What's new in ArcGIS 10.6](https://desktop.arcgis.com/en/arcmap/10.6/get-started/introduction/whats-new-in-arcgis.htm)
- [ArcGIS Best Practices](https://doc.arcgis.com/en/arcgis-online/reference/best-practices-share.htm)

**Potential items for How To's**
- [ArcGIS Desktop Resources](https://dcpplanningcoordination.github.io/dcp-guide/portfolio/gis-arcgis-resource-doc.pdf)
- [ArcGIS Online Resources](https://dcpplanningcoordination.github.io/dcp-guide/portfolio/gis-arcgisonline-resource-doc.pdf)
- [How to Make ESRI Desktop ArcMap Faster](https://github.com/ncss-tech/geo-pit/wiki/How-to-Make-ESRI-Desktop-ArcMap-Faster)

**Comment by croswell81** [comment]
Added links for updated ESRI guides, AGO, and CARTO
