### ISSUE TITLE
Z: Upgrade Pictometry to 2019

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#432]
###
**Upgrade Pictometry to 2019**

**2/27/19 ** - MC updated PctViewerSettings2019 in G drive resources folder - config file may require update as well. The we can test

**2/10/20 ** - Need to update PictViewerSettings.txt and configuration.bat files for 2019 and retest

**1/29/20** - 2019 Pictometry is available on T drive - ArcMap is crashing for both MC & AF using either 2017 or 2019 Pictometry

**11/17/20** - Will be switching to CONNECT plugin. Now access imagery in cloud instead of T drive. DCP has 40 CONNECT licenses.

 - [x] Reach out to GIS Users to see who is interested in CONNECT license
 - [ ] Set up CONNECT accounts

Initial work (before CONNECT):
- [x] GIS Team receive hard drive from DoITT (12/5/19)
- [x] PCNS (Hernan) upload data to T drive (1/24/20) - removed 2015 data 
- [x] Confirm license with EagleView 
        - [x] call Laura Mondo (585) 259-9871 for license info
 - [ ] Notify GIS Users (w/ PCNS ) of update available and instructions to access
     - [ ] deploy settings and config file for users (If possible)

**Comment by aferrar** [comment]
**3/10/2020**
Tested using 2019 imagery with only one crash during the software's first launch. All subsequent executions functioned appropriately. Matt tested as well as did not receive crashing either. 

We would like to run a small amount of continued testing on Matt's machine and then attempt to test on another user's machine other than Matt or myself. If this test user experienced no crashing, I believe we can communicate to PCNS that this is ready to be distributed.

**Comment by aferrar** [comment]
Matt and Connor (transp div) tested Pictometry 2019 on their work machines and experienced crashing. Need to investigate what is different with their machines that results in this type of behavior.

**Comment by croswell81** [comment]
3/25/2020: Placing On-hold until PCNS has more time to work with GIS team on troubleshooting.

**Comment by croswell81** [comment]
**10/21/20**

Met w/ Eagleview several times, no resolution on ArcMap crashing issues. Was granted a test license for Pictometry Connect (web) plugin. This works and does not crash ArcMap. Asked if Eagleview could provide additional licenses for Connect. This is possible but they need to know how many. Thinking of asking for 10 - 15 but want to reach out to other agencies to find out their experiences with Pictometry.

Lynn is reaching out to other agencies:
-  NYCEM experienced same crash issues - eventually purchased 100 Connect licenses $3300/year
-  DOITT not aware of issue (they mostly use connect)
-  need to check w/ DPR

**Comment by croswell81** [comment]
Requested 40 CONNECT licenses from Eagleview - which were granted.

Chris Rado (DOITT) sent Matt admin info, credentials and and link to create DCP CONNECT accounts.

Asked staff to send email to GIS Team if interested in having a CONNECT account in November GIS Newsletter. If we do not get much of a response will send a focused email.

**Comment by croswell81** [comment]
3/2/21 - Sent notice to users via GIS Newsletter several times. No users reached out about having CONNECT set up. Closing issue.
