### ISSUE TITLE
D: Develop Census Pipeline for PFF 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#439]

**Comment by SPTKL** [comment]
- complete
- in review: still need to tweak some of the metadata mapping

**Comment by SPTKL** [comment]
- decennial: 99% complete, Erica needs to check the median calculations (which are done before she joined, so we had some major calculation differences) 
- acs: 99%  complete, all issues resolved, in staging and waiting for manual review

**Comment by AmandaDoyle** [comment]
Keeping this open until we receive final sign off from Erica

**Comment by SPTKL** [comment]
decennial is complete
acs is complete, remaining issue in lab's court
