### ISSUE TITLE
The Guide - Link/button url audit

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#448]
A table with outstanding items (broken/dead links) is located on the GIS G drive under guide directory as link audit report. 

**Next step is to confirm the need for changes on non-changed links with their respective project owners**

Previous task included: (see #376)
Generated a Guide link report (comprehensive of all links on all pages) with a table recording:
* The page on the guide where the link lives
* The section of the page where the link lives
* (If button) the text associated with the button link
* The link that was previously assigned to the text/button
* Whether the link got updated in this audit (if no, gives a reason for why it was not updated [i.e. needed to consult another division/unit prior to doing so, etc])
* If updated, the new link that was used to update. If not, "no link"
* Planning Coordination github group needs to be moved into DCP organization.

**Comment by aferrar** [comment]
**02/25/2020**

Reached out to Amber in Planning Coordination regarding how they would like to handle outreach for making these changes. Awaiting response.

**Comment by croswell81** [comment]
Waiting on next steps to proceed - need to meet with Planning Coordination. Lynn will follow up with Amber.

**Comment by croswell81** [comment]
Meeting with Planning Coordination on 4/10 to discuss next steps with the Guide. Will reopen based on outcome of that meeting.

**Comment by croswell81** [comment]
Closing - The Guide was transitioned over to SharePoint and links were checked
