### ISSUE TITLE
E: Adult Use Establishment Analysis

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#451]
Working off of the discussion we had today (Thursday, Feb 20) conduct the analysis that answers the question: What is the maximum number of adult use establishments that can be sited in NYC?  Start with a neighborhood.

Deliver an initial analysis by Wednesday.

**Comment by AmandaDoyle** [comment]
@croswell81 provided the data to data engineering today
The team can start working on this on Monday

**Comment by mgraber** [comment]
Repo: https://github.com/NYCPlanning/aue

**Comment by AmandaDoyle** [comment]
Carrying over until we close out the last task

**Comment by AmandaDoyle** [comment]
Saying that this is completed because we successfully built the process and the results with first round of data have been reviewed and okayed.  We will just rerun when we receive updated data
