### ISSUE TITLE
K: Update EDM page of The Guide

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#461]
Met with Matt and Lynn on 02/24/2020 to discuss modifications to the EDM page of The Guide. Have implemented all discussed changes except for the WPAA spotlight description. Need assistance for proper description of the dataset.

List of changes that have been implemented:
- Moved all pdfs related to resource documents to the Q: drive
- Removed Mapping & Analytical Tools blurb
- Made all mapping tool item descriptions more understandable / less technical
- Changes Guides & Forms to Best Practices. Removed all resources except for staying organized resource
- Replaced staying organized powerpoint file with pdf version
- Asked Baiyue to include an image for his blog posts lacking images (which he implemented today, as well)
- Emailed Amber from Planning Coordination to request input on EDM button placement within main splash page.

**Comment by aferrar** [comment]
**3/2/2020**

* WPAA spotlight description updated.
* Pictometry tools description updated.

**Comment by aferrar** [comment]
Meeting with Planning Coordination and ITD/EDM through Teams scheduled for **3/17/20** to discuss further implementations of EDM draft page and administration of The Guide resources moving forward.

**Comment by croswell81** [comment]
Lynn to find out from Amber when we should meet about next steps. No progress can be made until we meet with Planning Coordination.

**Comment by aferrar** [comment]
Met with Amber on 4/17. Reviewed EDM page and got approval from her. Have a meeting tomorrow to further discuss layout of EDM page button on The Guide homepage. Also provided instructions for creating a staging site for Planning Coordination to make changes on.

**Comment by aferrar** [comment]
Need to come up with 3 draft locations for the EDM page button on The Guide homepage to provide to Planning Coordination

**Comment by aferrar** [comment]
Create draft layouts and sent to Amber, Matt, and Lynn for review.

**Comment by croswell81** [comment]
Moved to The Guide on SharePoint. Closing item.
