### ISSUE TITLE
J: Transition resource documents and gis materials to online platforms

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#481]
Need to transition documents from network file system to shared cloud platforms (sharepoint/teams/etc). Resources to be transitioned:

EDM division SharePoint
- [x] GIS resource documents
- [x] GIS help tracking sheet
- [x] transfer GIS SDE back up data to EDM SharePoint (not exchange) 

Exchange on SharePoint
- [x] EDM/GIS resource docs
- [x] GIS Layer Packages (LPKs) for at home use 
- [x] ArcGIS at home installation zip and instructions

**Comment by aferrar** [comment]
Staged preliminary pdfs on G for review

**Comment by croswell81** [comment]
Met w/ Lynn on 4/3:

- Lynn to review Resource docs

- 2.5 GB of data (missing imPACT)

Move to Sharepoint Exchange once approved

**Comment by aferrar** [comment]
4/21/2020

Uploaded remaining backup files to sharepoint. Believe this can be closed.

**Comment by croswell81** [comment]
LiDAR raster files were too large to upload. Will not back up since they are on open data.
