### ISSUE TITLE
General repo cleanup

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#487]
- [x] Archive old/unused repos and branches
- [x] Add missing descriptions to GitHub repos, and always include the full name of a dataset

**Comment by mgraber** [comment]
Archive these. If they are old versions of a current repo, include working repo name in the description.
Only repo admins can do this.
- [ ]   [db-housing](https://github.com/NYCPlanning/db-housing)
- [ ]   [db-housingdev](https://github.com/NYCPlanning/db-housingdev)
- [ ]   [db-pad](https://github.com/NYCPlanning/db-pad)
- [ ]   [db-zoning](https://github.com/NYCPlanning/db-zoning)
- [ ]   [db-scacapitalprojects](https://github.com/NYCPlanning/db-scacapitalprojects)
- [ ]  [db-geocode-bins-tpad](https://github.com/NYCPlanning/db-geocode-bins-tpad)
- [ ]  [db-atomicpolygon-qaqc](https://github.com/NYCPlanning/db-atomicpolygon-qaqc)
- [ ]  [db-geocode-addresspoints](https://github.com/NYCPlanning/db-geocode-addresspoints)
- [ ]  [db-geocode-housing-tpad](https://github.com/NYCPlanning/db-geocode-housing-tpad)
- [ ]  [db-pluto-inthewild](https://github.com/NYCPlanning/db-pluto-inthewild)


What are these? Are they in active use?
- [ ]  [db-simple-geom-editor](https://github.com/NYCPlanning/db-simple-geom-editor)
- [ ]  [db-retailfoodstores](https://github.com/NYCPlanning/db-retailfoodstores)
- [ ]  [db-civic-data-loader](https://github.com/NYCPlanning/db-civic-data-loader)
- [ ]  [db-airflow-dags](https://github.com/NYCPlanning/db-airflow-dags)
- [ ]  [db-softsite-analysis](https://github.com/NYCPlanning/db-softsite-analysis)
- [ ]  [db-ceqr-acs](https://github.com/NYCPlanning/db-ceqr-acs)


Add descriptions and/or more thorough README
- [ ]  [db-zoningtaxlots](https://github.com/NYCPlanning/db-zoningtaxlots)
- [ ]  [db-melissa](https://github.com/NYCPlanning/db-melissa)
- [ ]  [db-pad-validation](https://github.com/NYCPlanning/db-pad-validation)
- [ ]  [db-doe-significant-utilization-changes](https://github.com/NYCPlanning/db-doe-significant-utilization-changes)
- [ ]  [db-decennial](https://github.com/NYCPlanning/db-decennial)

**Comment by AmandaDoyle** [comment]
db-pluto-inthewild was a project I started with the idea of getting people to make pull requests that included lists of projects using PLUTO, but I never setup the framework or promoted it

**Comment by AmandaDoyle** [comment]
Add link to most updated repo for deprecated repos and make obvious that it's not in use
