### ISSUE TITLE
General: documentation

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#491]
- [ ] Consolidate and update our within-team documentation. This might include a high-level overview of the products we work on, and coming up with a standard way of describing their level of stability. It would be helpful to standardize an input data tracker/info sheet between products, too.  Once audience would be a new team member

**Comment by mgraber** [comment]
| Dataset | Description | Business Owner  | Production Cycle | Stability | Source Data Tracker | Documentation |
| -------- | ----------- | ----------------- | ----------------- | -------- | -----------------------  | ----------- |
|                |                      |                                |                                |                |                                            |                     |

**Comment by mgraber** [comment]
Stability hierarchy:

- Stable: gets regular updates. Code changes and enhancements do not happen with every release, and instead occur in scheduled sprints. The bulk of the build process and QAQC are no longer done by data engineering.
- Frequent enhancements: While this data gets produced routinely, few updates occur without hands-on refactoring of the code. The production of this dataset is still controlled by data engineering.
- In development:  This dataset is currently being developed. It has not settled into a routine production schedule yet, and may experience major overhauls between versions.

@AmandaDoyle @SPTKL Thoughts?

**Comment by mgraber** [comment]
https://data-engineering-doc.netlify.app/#/

**Comment by SPTKL** [comment]
I'm thinking we might need a project overview page (and there's space for that), maybe we can start brain storming about the layout in a markdown
