### ISSUE TITLE
General: Data analysis

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#506]
Learn more about our data products and take the time to do some data exploration and conduct open ended analyses.  Maybe this turns into a mini blog post.

**Comment by mgraber** [comment]
Running list of analysis ideas:
* Use DOB job characteristics to predict time-lag between date-filed and other status dates
* Comparison of predominant facility types and demographics of an area (by census geography or NTA). Using facDB and PFF or ACS.
* Colocation of facility types. Does spatial correlation align with fac groups or subgroups? Are facilities of the same type typically located near each other?
* PFF pipeline aggregates tract-level data into NTAs. If we were to use the same suite of variables with a contiguity-constrained clustering, to what extent would the resulting clusters align with NTA boundaries?
* Some kind of comparison between LION and TIGER for NYC streets. What are the patterns in where they are different? Could become a blog post about the shortcomings of a one-size-fits-all system and why city-specific data products are important.

**Comment by SPTKL** [comment]
+ compare LION with OSM and maybe figure out a workflow to contribute to OSM (current OSM data sources in the US https://wiki.openstreetmap.org/wiki/Category:Data_sources_from_the_United_States)

**Comment by SPTKL** [comment]
## Microsoft Building Footprints
https://github.com/microsoft/USBuildingFootprints
