### ISSUE TITLE
J: PLUTO Improvements 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#508]
Start building out the following PLUTO improvement projects from research
[#148](https://github.com/NYCPlanning/db-pluto/issues/148) 
[#146](https://github.com/NYCPlanning/db-pluto/issues/146)

**Comment by mgraber** [comment]
Links above are in wrong repo.
https://github.com/NYCPlanning/db-pluto/issues/146
https://github.com/NYCPlanning/db-pluto/issues/148

**Comment by AmandaDoyle** [comment]
Number of buildings is complete.
Irregular lot - still in brainstorming phase (but that's okay)
