### ISSUE TITLE
J: Create volunteer site webapp for HRA

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#517]
Needed to create a prototype web application for HRA/DSNY for showing potential volunteer accessibility to feeding site/food pantry locations.

Macrotasks
- [x] Build prototype [site](https://dcp.maps.arcgis.com/apps/webappviewer/index.html?id=bd2917566b274630aba8124b5f734c9d)
- [x] Preview to Lynn 
- [x] Preview to stakeholders
- [x] Implement stakeholder feedback
- [ ] Implement stakeholder upload process for updating data

Microtasks
- [ ] Research potential use of Geosearch (currently looking into this - AF)
- [ ] Implement future stakeholder feedback

**Comment by croswell81** [comment]
Based on meeting with HRA:
 - [x] Replaced DCP logo w/ NYC logo (also changed color theme to blue from orange)
 - [x] Removed Direction functionality - uses credits (if we want to add back AF figured out how to activate without needing AGOL login)

**Comment by croswell81** [comment]
Closing this since Lynn is working out data issues with HRA. We can open a new issue for Launching the app if it goes live
