### ISSUE TITLE
J: ArcGIS Online Dashboard

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#531]
Emulating community profile labs site in arcgis online dashboard format, Focusing on these topics first and then moving to incorporate more as move forward:

Demographics - ACS_NTAs
Land Use / Built Environment  - MapPLUTO
Health Data from Matt
COVID Data from Matt
Facilities - Filtered (maybe by food pantries)

**Comment by aferrar** [comment]
Have an almost complete demo ready for review and suggestions. Moving forward need to:

- [ ] Fix the Zoning chart by creating aggregate zoning fields in CD feature layer
- [ ] Rename Neighborhoods search to NTA name search (confirm these are actually NTA names)
- [ ] Demo to Lynn/Matt and get feedback. Determine where this project is going

**Comment by aferrar** [comment]
Completed all quality fixes. Waiting for opportunity to demo for feddback and further info as to how the dashboard will be used.

**Comment by croswell81** [comment]
Closing as this was not picked up to go live.
