### ISSUE TITLE
Pickup: GRU QAQC - DCM

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#535]
Check DCM names against Geosupport - function 1N, pick up borough code spatially

**Comment by SPTKL** [comment]
where can we find DCM @croswell81 @aferrar

**Comment by AmandaDoyle** [comment]
Street width layer, run street name through 1N
Need to get data from GIS
Reason: look for misspellings between files

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/db-gru-qaqc/issues/22
