### ISSUE TITLE
Pickup: GRU QAQC - in PAD and not in Footprints

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#536]
In PAD with non-million BIN, but no footprint

**Comment by AmandaDoyle** [comment]
GRU has to give us a numbering scheme of BINs to ignore / not process

**Comment by mgraber** [comment]
This is implemented, but times out when running on GitHub actions.

**Comment by mgraber** [comment]
- [ ] Try moving SQL from python to bash

**Comment by SPTKL** [comment]
NYCPlanning/db-gru-qaqc/issues/23

**Comment by mgraber** [comment]
Time-out error fixed. Results and versions are linked in the README.
