### ISSUE TITLE
Pickup: GRU QAQC - verify address points in PAD

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#537]
Run addresses for address points through function 1A to verify that the address is in PAD

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/db-gru-qaqc#check-that-cscl-derived-address-points-exist-in-pad

**Comment by mgraber** [comment]
This was rerun on 2020/05/13 with updated address point data. Updated results and version list are linked in the README.

**Comment by SPTKL** [comment]
reran with 20B geosupport and 20B PAD
