### ISSUE TITLE
Pickup: GRU QAQC - SAF vs 1A

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#538]
SAF vs 1A (check that alternative addresses are in PAD; note that there are15 different SAF layouts)

**Comment by AmandaDoyle** [comment]
GRU will point us to SAF files, provide document w/ what to use from each file

**Comment by mgraber** [comment]
https://github.com/NYCPlanning/db-gru-qaqc/issues/24
