### ISSUE TITLE
J: PLUTO publication collaboration 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#539]
Work with GIS to bring Esri process into build process so that DE can run end to end build of PLUTO

**Comment by SPTKL** [comment]
- [ ] shoreline clipping
- [ ] export as file geodatabase
- [ ] enforce strict schema

**Comment by SPTKL** [comment]
https://edm-publishing.nyc3.digitaloceanspaces.com/db-pluto/latest/output/mappluto.gdb/mappluto.gdb.zip

**Comment by AmandaDoyle** [comment]
Major workflow is complete.  Might need to do finalize code to handle final schema details.
Metadata creation will need to be done by GIS for now.  DE will look into metadata creation
