### ISSUE TITLE
K: Release LION/Districts 19B on Bytes/Open Data

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#55]
Release LION/Districts 19B on 
- [x] SDE/M drive
- [x] The Guide
- [x] Bytes
- [x] Open Data
- [x] AGOL

**Comment by croswell81** [comment]
@aferrar please update when the Guide and AGOL are complete and then close out

**Comment by aferrar** [comment]
Updated LION and Districts metadata PDFs on The Guide and AGOL.
