### ISSUE TITLE
ZTLDB - add Mechanical Void field

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#57]
Add binary Mechanical Void field to indicate if a tax lot if part of a Mechanical Void area.

**Comment by AmandaDoyle** [comment]
Refers to this isssue
https://github.com/NYCPlanning/db-zoningtaxlots/issues/16

Cannot move forward until we receive instruction from @croswell81

**Comment by croswell81** [comment]
Closing - one time data share instead of new field added to ZTLDB
