### ISSUE TITLE
L: POPS Open Data tasks

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#66]
Need a script to programmatically process the POPS data for Bytes and Open Data.
- [x] create a shapefile from csv
- [x] process and package for Bytes/Open Data (naming convention, update metadata, zip files)
- [x] update layer file metadata (internal only)

Internal procedures (Not for Open Data)
- [x] move new shapefile to SDE PROD
- [x] create a layer file for M Drive
- [x] create documentation

**Comment by aferrar** [comment]
Currently using the Background directory for generating layer file on M: drive and updating associated metadata information until M: drive re-structuring issue is addressed with a more appropriate location. Naming convention: Privately Owned Public Spaces.lyr / Privately Owned Public Spaces.xml
