### ISSUE TITLE
Housing/Dev DB Dashboard w/ HED 

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#668]
Met with HED to discuss potential of setting up a Housing/Dev DB dashboard.

HED had inquired about Open Data "DataLens" or streamlit framework for dashboard). GIS suggested AGOL as an alternative for dashboard creation. Would need to reach out to Open Data team for more information on "DataLens". 

- [ ] Schedule meeting with HED/Open Data to discuss the possibility of using DataLens pages for dashboard (if needed)
- [ ] Determine with HED which dashboard platform is most appropriate moving forward
- [ ] Setup location for HED to update data (SDE/GDB/etc/somewhere GIS can access)
- [ ] Write script that picks up HED updates and properly distributes to necessary dashboard platform to update dashboard data sources
- [ ] Determine frequency for script execution / communication intervals for HED to notify GIS of available updates 
- [ ] Create documentation w/ Matt for script that will distribute all necessary data

**Comment by croswell81** [comment]
**12/16/20**

Focus has shifted to releasing public dataset. GIS team needs to discuss if Housing/Dev DB dashboard or application is still needed. Placing On-Hold.

**Comment by croswell81** [comment]
Closing - Housing division will create there own dashboard if still needed.
