### ISSUE TITLE
Z: BYTES GeoJSON fix

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#717]
Issues reported by some users with geojson link for mappluto, lion and lion node links with services timing out.

Run test to recreate issues
    - [x] MapPLUTO - Failed
    - [x] LION - Failed
    - [x] LION Node - Passed (did not time out)

Checked to see if this can be resolved by modifying the admin settings for those feature services using a token. This did not allow us to adjust the timeout settings.

Requested MapPluto and LION GeoJSON links be removed from Bytes.

**Comment by croswell81** [comment]
12/11/2020 - A Possible solution: Have current functioning links sourced to arcgishub open data domain (don't think this will work)
