### ISSUE TITLE
Z: Housing/Dev DB Data Automation

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#721]
HED has worked w/ DE to produce new Housing/Dev Database, which pulls data from DOB housing permit data via open data and reclassifies, cleans and aggregates that data. First release of Housing/Dev DB (20q2) was created manually. GIS Team needs to create scripts to automate that process. 

- [x] Write script(s) to perform the following tasks:

    - [x] Pull raw data from DE [github](https://github.com/NYCPlanning/db-developments)
    - [x] Process data to create datasets for both public and internal formats with appropriate schema and metadata
    - [x] Distribute data to necessary platforms (BytesProd, SDE, AGOL, Carto, Digital Ocean)

For additional information:
See Housing/Dev DB data production #720
See Housing/Dev DB dashboard: #668

**Comment by aferrar** [comment]
Completed all requirements per Housing document created by Matt. Reviewed outputs with Matt. Awaiting further instructions prior to closing issue.
