### ISSUE TITLE
D: M drive DTM cleanup

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#728]
After data review: 
- [x] remove DTMLocal.gdb from M drive where layers are located
- [x] create layers for datasets previously represented in DTMLocal.gdb. Source to feature dataset on SDE

**Comment by croswell81** [comment]
Moved DTMlocal.gdb to x drive. Will monitor to see if there were any issues removing from M:\GIS\DATA\DTM.
