### ISSUE TITLE
D: Confirm various Cyclomedia installations

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#729]
Lynn discovered GlobeSpotter for ArcGIS Desktop Cylcomedia extension no longer functional due to Adobe Flash end-of-life (EOL). Confirmed that Street Smart for ArcMap extension is still functional but it seems there was a limited rollout of the software as it is not currently installed on Lynn's machine.

Need to:
- [ ] Confirm PCNS has the appropriate documentation/installation files for proper rollout of:
    - [ ] Street Smart for ArcMap
    - [ ] Street Smart for ArcGIS Pro
- [ ] Confirm proper installation of Street Smart for ArcMap extension agency-wide
- [x] Confirm proper installation of Street Smart for ArcGIS Online (widget only - see comments)

- [ ] PCNS to remove GlobeSpotter extension from all PCs w/ ArcGIS

**Comment by aferrar** [comment]
Confirmed with Cyclomedia that ArcGIS Online Street Smart app is deprecated and no longer available. Current AGOL functionality is limited to the Street Smart widget which requires ArcGIS WebApp Builder (Developer Addition). This limits rollout to individual applications and requires hosting on internal server (not a smooth build process for planners). Did discuss with Cyclomedia support the potential for Street Smart becoming an approved ESRI application which would allow users to use it directly from ArcGIS Online without the need for self-hosting. No timeline was given for this though.

**Comment by croswell81** [comment]
Expired
