### ISSUE TITLE
Create Facilities DB Script

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#732]
Create a script to generate, package and distribute Facilities Database:

 - [ ] pull raw data from https://github.com/NYCPlanning/db-facilities
 - [ ] process raw data to update schema
 - [ ] generate fgdb
 - [ ] apply updated metadata via xml (or can use the most recent fgdb)
 - [ ] generate shapefile version
 - [ ] generate csv
 - [ ] package fgdb, shp, csv w/ DD and Readme

Distribute to SDE and update lyr file xml could be another script.

**Comment by aferrar** [comment]
Waiting on updated DE process to be able to pull from latest repo implementation

**Comment by croswell81** [comment]
Moved to Script Enhancements
