### ISSUE TITLE
2021 Open Data Compliance - Website Data (Tab B)

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#750]
Identify any data found on public websites maintained by or on behalf of your agency. Agencies are required to make all such data that is also shared publicly on NYC Open Data

Table 1
In this table, fill in information on newly identified datasets on public websites maintained by or on behalf of your agency. You can consult Table 2, below, for datasets that were previously identified in 2020. Every field for each newly identified dataset must be completed.

This table is prefilled with the list of website datasets that were contained in the 2020 Open Data Plan. Filter for your agency in cell A26, and review this table for accuracy. For this table: 
1. Specify whether each listed dataset is automatically updated on your agency's website
2. For datasets that have been published to NYC Open Data since the 2020 Open Data Plan, please provide the new Open Data URL
3. Note any other changes that need to be made in the yellow highlighted "Updated Information" column

**Comment by aferrar** [comment]
Added recently released BYTES datasets to open data compliance sheet.

**Comment by croswell81** [comment]
Added Housing Database data on BYTES and Supermarket Needs Index
