### ISSUE TITLE
Fix publication for AGOL services

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#753]
EDes, MIH & Lion_Node: need to test creating new feature service / service definition to see if our AGOL publish script will update new services.

Also need to create new services for all 2020 Census files:

**Comment by croswell81** [comment]
LION Node and new 2020 Census files have been created.

Need to troubleshoot with ESRI why Edes and MIH are not updating.

**Comment by aferrar** [comment]
All services fixed yesterday. MIH and E-Des require renaming prior to running script. LION Node and 2020 census files can be run without modification. There is potential for recreating MIH and E-Des services to not require a renaming, but we are holding off until future script modifications are needed.
