### ISSUE TITLE
LPC script fix

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#763]
Adjust LPC_scrape script so it exports the Designated and Calendared Buildings and Sites dataset to a geodatabase.

Currently when we pull that dataset from Open Data portal the dataset does not copy correctly. We believe this is due to the original file in open data is not a shapefile and Socrata platform conversion is corrupting the file.

We reached to both open data and LPC but neither have been able to resolve the issue on their end.

**Comment by aferrar** [comment]
Resolved yesterday by including additional gdb step. Also updated LPC datasets and uploaded to DigitalOcean yesterday
