### ISSUE TITLE
K: PSA issues

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#8]
- [x] Addresses from Doug with wrong geotype for PSA 
- [x] Add 4 addresses that don't geocode
- [ ] Change implementation from 1 byte to 2 bytes? GEO needs to know by 6/17.

**Comment by TomMCosta** [comment]
Lynn needs to provide Doug with a deadline for letting GEO know if 2 bytes is acceptable for NYPD.
