### ISSUE TITLE
Enhancements and bug fixes to GRU QAQC

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#806]
Address these two issues for GRU QAQC repo
https://github.com/NYCPlanning/db-gru-qaqc/issues/257
https://github.com/NYCPlanning/db-gru-qaqc/issues/256

**Comment by damonmcc** [comment]
@fvankrieken are we good to close the two issues linked here and then this issue?

if you're waiting for Vlad to test em out and give feedback, no worries with keeping em open

**Comment by fvankrieken** [comment]
Waiting on meeting with Vlad, and I wouldn't really call https://github.com/NYCPlanning/db-gru-qaqc/issues/257 done, that didn't really get addressed in my prs
