### ISSUE TITLE
Building Footprint scrape/pull script troubleshooting

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#832]
Proposed troubleshooting steps for Building Scrape script:

1. Resolve python environment - compare docstring in script with .py called in task scheduler

2. Test proxy values with standalone python requests script - confirm that scripts on our internal network can hit the open data portal API endpoint

**Comment by croswell81** [comment]
This is not an issue with the script, Jack can run without issue. Matt has issue running python from both VS code and PyCharm

**Comment by jackrosacker** [comment]
As an update: initial attempt to run this script on my machine resulted in an error that pointed to the confiParser call to the proxy variables. Updating the proxy variable naming convention from _http: <value>_ to _http_proxy=<value>_ allowed the script to run successfully.

Run successfully with python 2.7
