### ISSUE TITLE
Task Scheduler XML Cleanup

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#834]
### Goals: 
1.  Ensure we have clean XMLs for scheduled tasks until we are able to link scheduled tasks to a single server rather than multiple versions on separate machines
  - **Proposed:**
    - [x] Identify a single source of truth location for Task Scheduler XML files
        - G:\ScheduleTasks\Scheduled Task XMLs
    - [x] Delete or archive all other copies
    - [x] Review XMLs
    - [x] Review Task Scheduler settings on all three of our machines, update as needed
        - [x] Create GIS folder in Task Scheduler
        - [x] Delete any old scheduled tasks from Task Scheduler (if in root directory)
        - [x] Import all new XMLs from G drive to new \GIS subfolder
    - [x] (Optional) Connect Task Scheduler apps to network drives, allowing for a single source of truth DONE
    - [ ] ~~(Optional) Commit XML location to Github [is this a security issue?]~~
  - **Resources:**
    - [freecodecamp XML viewer resources](https://www.freecodecamp.org/news/how-to-open-an-xml-file/)

**Comment by croswell81** [comment]
Tasks I cannot edit/delete in my task scheduler:

- CopyDCM
- MIH2SDE_Distribution

Need PCNS to help troubleshoot how to get rid of those tasks (admin only?)
