### ISSUE TITLE
Fix CopyZoningGeoMaps script

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#837]
### Issue Description:
CopyZoningGeoMaps.py script is throwing an error:

```
2023-01-14 00:00:22    PYTHON ERRORS:
Traceback Info:
File "CopyZoningGeoMaps.py", line 21, in <module>
arcpy.CopyRaster_management(src, dest)

Error Info:
ERROR 000601: Cannot delete G:\Connections\arcsdegis\sde@GISPROD.sde\GISPROD.SDE.GeoreferencedNYCZoningMaps.  May be locked by another application.
Failed to execute (CopyRaster).
```
- [x] Troubleshoot script
~~- [ ] Find/update/create documentation~~
~~- [ ] Verify metadata updates - at least parity with previous iteration~~
- [x] Create .ini, migrate hardcoded values
- [x] Add py version check clause
- [x] Add docstring
- [x] Archive older files
~~- [ ] Prep for Github~~
  ~~- [ ] Create .gitignore~~
  - [x] Create .ini template
  ~~- [ ] Create environment.yml~~
  ~~- [ ] Commit to Github~~
- [x] Prep for scheduling
  - [x] Create .bat file [[0]](https://gist.github.com/maximlt/531419545b039fa33f8845e5bc92edd6) [[1]](https://stackoverflow.com/questions/24678144/conda-environments-and-bat-files)
  ~~- [x] Add to Task Scheduler~~
  ~~- [ ] Export XML to central location~~
~~- [ ] (possible) Restructure CopyZoning and CopyZoningGeoMaps project folders, with eye to Git commits~~
- [x] Finalize steps enumerated in [Review CopyZoningGeoMaps.py for deprecation](https://app.zenhub.com/workspaces/edm-project-management-5cd1a00fc5fef1637967aabb/issues/gh/nycplanning/edm-overview/863)

**Comment by jackrosacker** [comment]
Initial testing showed that the destination file that was to be overwritten was corrupted. No concrete reason for this corruption has been discovered, but the new script does not appear to have the same issues

**Comment by jackrosacker** [comment]
Tested installing conda environment on G drive in \PROJECTNAME\env\ENVNAME
- cloning to this location appears to work [[0]](https://edcarp.github.io/introduction-to-conda-for-data-scientists/02-working-with-environments/index.html)
- next steps: 
  - test running scripts from this env
  - test running scripts from this env via batch file
  - test running scripts from this env from another machine/user/conda installation

**Comment by jackrosacker** [comment]
Successfully tested:
* cloning a conda environment to \PROJECTNAME\env\ENVNAME - **note that this is on a network drive**
* using a .bat script to activate and execute the python script
Next steps:
* duplicate to a shared network drive location, test executing .bat from @caseysmithpgh 's  machine pointed to same location
Again - cloning was very slow.

**Comment by caseysmithpgh** [comment]
Clarification: @jackrosacker is the .bat script in the CopyGeo repo on G/Scripts? Do you think it would be best for me to install anaconda, or just use a pro conda env?

**Comment by jackrosacker** [comment]
Created .bat for this script. 

Next steps: test from Casey's machine

**Comment by jackrosacker** [comment]
Discovered this process was redundant with zoningAGO.py and the associated sde dataset. Completed steps in [Review CopyZoningGeoMaps.py for deprecation](https://app.zenhub.com/workspaces/edm-project-management-5cd1a00fc5fef1637967aabb/issues/gh/nycplanning/edm-overview/863) to finalize, and completing this task.
