### ISSUE TITLE
Project: PLUTO+

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#838]
Create a new dataset to enable more frequent data updates to PLUTO zoning fields to resolve issues for ZoLa users.  See repo [here](https://github.com/NYCPlanning/db-pluto-zola)

**Comment by damonmcc** [comment]
noting new approach:
- use PLUTO repo
- add a minor build pipeline

[ ] create new GHA action for minor build
[ ] create new yaml file to declare input dataset versions for minor build
[ ] create shell script to be called by GHA and ingest new yaml file

**Comment by AmandaDoyle** [comment]
Closed - created and delivered zoning only update of PLUTO
