### ISSUE TITLE
M: Prepare Digital City Map Files for Bytes/Open Data

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#84]
Three files to be included on Bytes and Open Data:
Remove the following fields from each .
- [x] Digital City Map (DCM) - Boro_nm, Feature_type , type, Source, Jurisdiction  and Ownership_status.
- [x] City Map Street Centerline (DCM_SCL) - Streetwidth, Official_street_name, Roadway_type, Boro_name, feature_status
- [x] City Map Change Index (NYMI) - app_num, Status, Effective, borocode, altmappdf, chg_type, scanned, project_name and filed_status.

*MC - Will add additional tasks next week*

**Comment by aferrar** [comment]
6/19/2019 - AF

Created temporary shapefiles from those on SDE PROD. Removed all fields except those stated for preservation in this Issue.
