### ISSUE TITLE
Morningside Heights Rezoning GIS tasks

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#846]

**Comment by caseysmithpgh** [comment]
Created Manhattanville Workspace Pro Project in GIS subfolder of G:/Projects/Manhattanville for analysis purposes

**Comment by caseysmithpgh** [comment]
- Proposed Commercial Overlays and Zoning Districts were completed yesterday and sent to Manhattan for approval. 
- "Segmented" Study Area has been created from dissolving the merged aforementioned features. 
- All layers have been reduced to the relevant study area. 
- Separate buffers were created for wide and narrow DCM selections
- Fields in PLUTO have been largely reduced to those relevant.
- Fields in schema workbook have been added to PLUTO layer
- Schema workbook was updated to include field names used in PLUTO layer

**Comment by caseysmithpgh** [comment]
**ITEMS FOR Manhattan/Zoning to Review:**
- [ ] CurrentZD is NULL (bc ZoneDist2 NOT NULL)
     -confirm by sending 4 bbls (tell them what ZDs the bbl is split between)
           - 1018810006, 1018810003, 1018810003, 1018800001

**Comment by caseysmithpgh** [comment]
Received feedback on lots split between proposed zoning districts from Kiyoshi yesterday. Before proceeding with with analysis we have 2 outstanding questions. 1. For lots that kiyoshi recommends should comply with regulations from two dif zds--what is the FAR/height that should be applied?  2. We still need wide/narrow recommendations from zoning.

**Comment by caseysmithpgh** [comment]
MEETING NOTES 4/12/23: Kiyoshi, Casey, Matt, Jose, Audrey
Tom Smith primarily assists on these types of neighborhood applications, reach out for examples or guidance. 

Asks: 
**Wide/Narrow**
For campus sites: No split lot calculations
Wide FAR gets applied to section of lot within 100 ft buffer 
Buffer needs to be 100ft from street front not centerline

**Split Lots**
Split Lots, see regulation 77-22 ZR
Pro rated FAR calculation (blended)
> 25 ft from split line, take larger % of lot regulations

**Soft Sites**
- matt to look into, kiyoshi doesn't believe this will be much of a factor
-jose identified 5 during previous analysis

Action Items: 
- [ ] create new buffer (get a hand full of street front to centerline measurements and extend buffer by that avg)
- [ ] select lots w/i new wide buffer
- [ ] get blended FAR calculation

**Comment by caseysmithpgh** [comment]
Next steps on split lots / wide splits after meeting with Matt:

- [ ] duplate rezoning area (pluto lots) before splits saved for current purposes
- [ ] add fields to proposed lots 
   - [ ] concat bbl [bbl - zd]
   - [ ] change value of ProposedZDApp value on splits

**Comment by caseysmithpgh** [comment]
Now that all non split lots have been assigned all defined values, we are going to add several fields for calculating split (pro-rated). The same approach will be assigned to existing and proposed conditions. **NOTE**: Formulas for Diff, Pct Built, NC vars will be different for split lots than they will be for non-split lots -- i.e. will use [Split_NumFloor] rather than [NumFloor].

Schema Needs:
- Lot Area (needs to be rejoined from PLUTO 23v3.1)
    - Confirm Lot Area is not NULL for any of our split lots.
- New Lot Area (split) == ShapeArea
- Lot Proportion == New Lot Area/Lot Area
- Split BuiltFAR == Built FAR * Lot Proportion
- Split NumFloors== NumFloors * Lot Proportion

**Comment by caseysmithpgh** [comment]
Deliverables:

- Non-Conforming by Reason
  - [ ] Existing Map
  - [ ] Existing List
  - [ ] Proposed Map
  - [ ] Proposed List
- Under built >50%
  - [ ] Existing Map
  - [ ] Existing List
  - [ ] Proposed Map
  - [ ] Proposed List
- Compliance Changes
  - Lots that will be brought into compliance (FC)
  - Lots that will be brought out of compliance (FC)
  - Lots that remain non-compliant (FC)
  - Lots that will be brought into compliance (BBL list)
  - Lots that will be brought out of compliance (BBL list)
  - Lots that remain non-compliant (BBL list)

**Comment by caseysmithpgh** [comment]
Initial deliverables were shipped to Mannhattan + Kiyoshi. 
-maps
-documentation
-data dictionary
-GDB

Temporarily placing issue in on-hold until Manhattan requests additional work items.

**Comment by caseysmithpgh** [comment]
- Symbology/Layout Edits
	- [ ] Add simple Zoning District outlines to Non-Conforming and Compliance Tracker maps
	- [ ] Change symbology to black for unchanged Commercial Overlay on Proposed Zoning map
	- [ ] Confirm accuracy of disappeared commercial overlay at 125th and Broadway – update map accordingly
	- [ ] Change color ramp of unchanged zoning districts to grey scale on Existing Zoning map
	- [ ] Requested: Legend changes for Proposed ZDs “R8 -> R9A”. Instead we can change the labels to reflect this (and do our best to reduce busyness). This cannot be added to the legend because of the R10A districts that were previously two different zoning districts. 
	- [ ] Streamline split lot symbology on Compliance Tracker map (change from red to grey dashed)
- Additional Deliverables
	- [ ] Table of BBLs by Proposed Zoning District – Compliance Tracker 
	- [ ] Walkthrough of using Soft site tool with MH

**Comment by caseysmithpgh** [comment]
Updated deliverables were shipped to MH today. They include an updated GDB, updated maps (including soft site maps, in place of >50% underbuilt), and bbl compliance tracker listed by ZD.

**Comment by caseysmithpgh** [comment]
### Updated deliverables shared with MHO yesterday prior to IDM 5/23/23:

- Updated Underbuilt 50% maps
- MIH applicable areas added to proposed soft site map
- Table of FAR changes by ZD
