### ISSUE TITLE
Maintenance: Troubleshoot Powershell/Conda inconsistency

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#852]
[https://app.zenhub.com/files/185426265/bb9921fe-1046-466b-9054-952e63e8e20f/download](https://app.zenhub.com/files/185426265/bb9921fe-1046-466b-9054-952e63e8e20f/download)### Issue:
Opening the PowerShell console or executing a python script in VS Code result in an initial series of errors that reference Conda in multiple places, as well as a shell.powershell hook and \\conda-hook.ps1. This is suggesting some system misconfiguration between Conda and PowerShell. 
- In VS Code, the initial run of a script will initiate the PS error and the script will not run. A second attempt will run the script successfully with no errors.
- Issue appeared around 2/1 or 2/2. 
- Issue appears on both Casey and Jack's machines. 
- System changes that occurred around the same time:
  - VS Code python extension was updated (this caused other python-specific issues that we have resolved)
  - Jack cloned a virtual environment onto a share drive for the first time
  - Possible Windows or related PCNS updates during this timeframe
  - ??

### Complete when:
1. Error does not appear in either VS Code or standalone PowerShell
2. Python script can run from the first attempt in VS Code, and do not require a second attempt

### Error message:
- Highlights:
`Traceback (most recent call last):
      File "conda\cli\main.py", line 143, in main
      File "conda\activate.py", line 1210, in main
      File "conda\activate.py", line 178, in execute
      File "conda\activate.py", line 166, in hook
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\J_Rosack\\AppData\\Local\\Temp\\_MEI178002\\conda\\shell\\condabin\\conda-hook.ps1'`

- Complete error messages are attached as text files [from pwsh](https://app.zenhub.com/files/185426265/1d6826d2-424f-40f7-9047-32f8cf02c1e8/download) and [from VS Code](https://app.zenhub.com/files/185426265/f73617f8-52ba-40aa-8eb2-c6e193da3fab/download) (both Jack's machine)

**Comment by damonmcc** [comment]
hey @jackrosacker! I'd meant to share this earlier but kept forgetting to

I've become a big fan of [pyenv](https://github.com/pyenv/pyenv) to do python installs and manage virtual environments. and [this is the walkthrough/reference](https://realpython.com/intro-to-pyenv/) that I keep going back to when I'm using it

hope it might be helpful for ya'll!

**Comment by jackrosacker** [comment]
> hey @jackrosacker! I'd meant to share this earlier but kept forgetting to
> 
> I've become a big fan of [pyenv](https://github.com/pyenv/pyenv) to do python installs and manage virtual environments. and [this is the walkthrough/reference](https://realpython.com/intro-to-pyenv/) that I keep going back to when I'm using it
> 
> hope it might be helpful for ya'll!

Thanks @damonmcc, this is a good pointer. We are tied to conda as our package manager for anything related to Esri products unfortunately, but pyenv may be a good lead for non-esri scripts

**Comment by caseysmithpgh** [comment]
This comment details initial details of conda/powershell/python extension in VS code problems. What is included took place prior to Jack realizing he was also having these issues, and our mutual update to VS code python extension. 

![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/1d7844aa-1a5d-4f76-8a86-7ee635e220ef)
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/acc1cd6f-c18f-4b75-a2b8-92fc5f11bbb6)
Attempting to troubleshoot LION_archive and am receiving the above notice in my powershell terminal. PROXY vars are empty. 

Two issues are presenting: VS code is not recognizing 2.7 python exe as a valid installation of python. (2) While in 3.7 clone env I am unable to connect to the SDE (dev or prod). 

Deleting VS code var from windows env vars. 
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/eb6db2d0-f224-4c8a-9999-ff9185d8496a) RESULT: no notable difference.

![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/96c39724-aea4-4718-9305-a327419be11e)

Python Extension Settings page:
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/62b77170-e515-4de7-8d15-1d000cc4774a)

**Comment by jackrosacker** [comment]
Partial fix:
* Ran 'conda init powershell' command in Anaconda Powershell Prompt
* 'conda-hook' and 'profile.ps1' error disappeared from both Powershell and the Powershell VS Code terminal
* (base) appears before prompt in both pwsh and VS Code pwsh terminal
* Potential issue: with conda initialized in pwsh, the GUI interpreter selection seems to be uncoupled from the active environment within VS Code. This feels like an issue so I:
* ran 'conda init powershell --reverse' to de-initialize conda from pwsh
* the initial error messages no longer appear, and scripts run at the first attempt. Interpreter can be set from GUI. Only remaining issue is the presence of this terminal error in VS Code: `conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program.` This shouldn't be a blocker and I'm inclined to consider this issue closed after we test Casey's environment

**Comment by caseysmithpgh** [comment]
Casey:

This week, Jack and I met and discovered that WindowsPowersShell/profile.ps1 was being stored in my OneDrive. We moved this back into my my Documents Folder--locally on C:/Users/../
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/6ff6e0be-1ec4-45ee-b2c6-46a12b2a68b4)
when the config file above is not entirely commented out the powershell error persists
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/a2335d61-14a4-4b8f-b6c7-8849bcd6c255)
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/b0438ede-95e4-4605-8add-35114e0f1c3b)
When the profile.ps1 is entirely commented out the error disappears, but conda is still not able to be successfully referenced:
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/2c725b95-f3ba-406e-9faf-cabd373adfc4)

**Comment by caseysmithpgh** [comment]
Lingering question: how does having remnants of old Anaconda install impact calling conda? Should I have PCNS install Anaconda?
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/aa27c67a-194d-4f05-9f5d-10d2b93e8227)

**Comment by jackrosacker** [comment]
Pending @caseysmithpgh 's request for a clean install of Anaconda from first couple weeks of March

**Comment by caseysmithpgh** [comment]
Followed up with PCNS, awaiting response. Both anaconda and git desktop install packages are staged in C:/setup as requested by pcns

**Comment by caseysmithpgh** [comment]
- PCNS helped install anaconda on my machine this morning. 
- I was able to open anaconda powershell prompt -- error on open persisted. 
- Ran conda init. 
- Closed and reopened prompt. 
- Error no longer printed on open. 
-In vs code with a python 2 interpreter open: no error, only had to hit run once.

**Comment by caseysmithpgh** [comment]
- PCNS helped install anaconda on my machine this morning. 
- I was able to open anaconda powershell prompt -- error on open persisted. 
- Ran conda init. 
- Closed and reopened prompt. 
- Error no longer printed on open. 
-In vs code with a python 2 interpreter open: no error, only had to hit run once.
