### ISSUE TITLE
P: July Open Data Update

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#86]
**Datasets Updated Monthly**

- [x] **Zoning GIS features & Sidewalk Cafe (fgdb/shp)** and **Georeferenced NYC Zoning Maps (fgdb)** 
    - [x] Pull data from TRD and update SDE PROD - Run *CopyZoning.py* and *CopyZoningPDF.py* scripts (for zoning & sidewalk cafe)
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoningGeoMaps* script (for Zoning Maps only)
  - [x] Process Files - Run  *Zoning and Sidewalk Cafe* tool (update metadata, package files for webteam)
  - [x] Update The Guide card
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Update CARTO - manually (implement script - Run *Import_Carto_Script.py* - after discussion w/ Labs)
  - [x] Update Open Data log and send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log and email Planning Coordination 

-----

- [x] E-Designation - shp/csv
  - [x] Manually move the E_GIS.txt file sent by Susan Wong to M drive and append the "as of date" from the email to the file name 
        -This can be sent multiple times per month (use latest one) 
  - [x] Process Files - Run  *Generate_EDesig.py* script (creates the shapefile)
  - [x] Process Files - Run  *- Distribute_EDesig_Apply_Metadata.py* script (update metadata, package files for webteam, push to SDE PROD, update lyr metadata)
  - [x] Update The Guide card
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Update CARTO - manually (implement script - Run *Import_Carto_Script.py* - after discussion w/ Labs)
  - [x] Update Open Data log and send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log and email Planning Coordination 
-----

- [x] Zoning Tax Lot Database (ZTLDB) - csv
  - [x] Receive notification from Lynn (or Amanda) that csv and metadata are QA'd and ready
  - [x] Zip the csv and pdf metadata
  - [x] Update Bytes (send email to Webteam)
  - [x] Update Open Data log and send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log and email Planning Coordination 
-----

**Ad Hoc Tasks**
- [ ] change the naming convention for all files created to match month of Publication Date (i.e. publication date = 05/29/19, than file should = nycgiszoningfeatures_201905shp), instead of the day it is run (edited) 
- [x] Update FRESH (Sam in HEIP received updated discretionary tax incentives boundaries from EDC. Will update GIS file and provide to GIS for July update)
- [x] Update Open Data table - add missing metadata links

**Comment by aferrar** [comment]
Open Data / MMR
* Copied the Open Data excel sheet and added changes for month of July. Haven't reached out to Open Data or internal contacts. Waiting for review since this is first time going through this particular cycle. 

Ad Hoc Tasks Update:
* Implemented naming convention change for month match for **E_Designation generation script**. Need to implement for **Distribution script**. Also still needs to be implemented for **MIH script**.
* Added all missing metadata links for those that were available on Bytes webpage

**Comment by aferrar** [comment]
08/09/2019
Ad Hoc Tasks Update:
* FRESH dataset packaged with metadata and ready for release. Waiting for additional dataset before notifying webteam (ZTLDB)
* ASTEP dataset packaged with preliminary metadata. Will not be released to public, but SDE version of dataset has been created and associated layer files created, as well.

**Comment by croswell81** [comment]
Closed out for July:

@aferrar you can work on this while I'm out:

change the naming convention for all files created to match month of Publication Date (i.e. publication date = 05/29/19, than file should = nycgiszoningfeatures_201905shp), instead of the day it is run (edited)
