### ISSUE TITLE
Resolve .lyr file access issues for DCP users

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#862]
Quick Summary:
- broken data links observed by multiple GIS users: Ibrahim, Hanif, etc.

**Comment by jackrosacker** [comment]
Results of troubleshooting w/ Ibrahim on 2/16
Takeaways:
•	It appears that Ibrahim's connection issues are isolated to his machine, and not his user account
•	The error messages and behavior noted point to clearly documented cases which have been resolved by installing an updated ODBC driver
•	It appears that SQL Server Native Client 11 is no longer used or necessary (not available from My Esri DL page, help articles allude to deprecation)
Next steps:
•	Install ODBC Driver v 18 on Ibrahim's PC and test connection
•	Else, try older versions of the driver and test again
Resources:
•	[Error: Connection was attempted with an older version of SQL Server client communications software that is not compatible with the SQL Server database server (esri.com)](https://support.esri.com/en/technical-article/000010759)
•	[Solved: Arcgis Pro 2.5 - SQL Database Connection - Esri Community](https://community.esri.com/t5/arcgis-pro-questions/arcgis-pro-2-5-sql-database-connection/td-p/113609)
![image.png](https://images.zenhubusercontent.com/63c70f3233c7931e09b40a81/af3222ac-a346-47b3-a87c-d3a110de33b6)

**Comment by jackrosacker** [comment]
### Updates:
Testing on two machines (Ibrahim and Hanif) has been successful so far. Installing the most up to date ODBC driver appears to resolve the lyr file/db connection issue
### Unverified:
- Possible that future installs may not need SQL Server Native Client 11.0. Documentation is unclear, but this driver appears to be older, and the functionality may be replaced by the latest ODBC driver
  - Small sample size, but Casey's machine is able to successfully connect to SDE data sources, and is only using an ODBC driver (Native Client is not installed)
### Next steps:
- Find remaining GIS users who are having this problem, implement fix ( @croswell81 how would you like to approach finalizing this? Options: Let users come to us, ask at GIS users mtg, add to newsletter etc.)
- Add updated driver steps to future GIS installs

**Comment by croswell81** [comment]
Rafael Berges confirmed he can access .lyr files in ArcGIS Pro
