### ISSUE TITLE
PublishTOAGOL Issues

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#864]
ERROR on Matt's Machine from 2/17/23:
Created g:\ScheduleTasks\PublishToAGOL\PyScripts\tempDir\NYC_City_Council_Districts.sd                                              US Census 2010.updated SD:   7786ad8ff0fa4376b126e0046c08f6f8https://www.arcgis.com/sharing/rest/content/users/DCP_GIS/publish{u'error': {u'messageCode': u'PUB_0047', u'message': u'User cannot overwrite this service, using this data, as this data is already a is already referring to another service.', u'code': 500, u'details': []}}                                                         referring to another service.', u'code': 500, u'details': []}}
Traceback (most recent call last):  File "g:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py", line 83, in <module>    execfile(updatePy)  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 507, in <module>    fsID = agol.publish()  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 217, in publish    print("successfully updated...{}...".format(jsonResponse['services']))
KeyError: 'services'
PS G:\ScheduleTasks\PublishToAGOL>

**Comment by croswell81** [comment]
When uploading 23B had to upload the following files manually because script failed to upload:

- LION
- LION_Node
- NYC_City_Council_Districts
- NYC_City_Council_Districts_Water_Included
- NYC_Election_Districts
- NYC_Election_Districts_Water_Included

**Comment by croswell81** [comment]
CPDB is also not working in the PublishToAGOL scripts (_update_ini.py)

Received this error message:
G:\ScheduleTasks\PublishToAGOL\_CPDB\Capital_Projects_Database_points.mxd
G:\Connections\arcsdegis\os@GISPROD.sde\GISPROD.SDE.DCP_CAP_CPDB_projects_pts
2831: maxRecordCount
creating xml file for Capital_Projects_Database_points
Traceback (most recent call last):
  File "G:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py", line 80, in <module>
    config.write(configfile)
  File "C:\Python27\ArcGIS10.6\lib\ConfigParser.py", line 412, in write
    key = " = ".join((key, str(value).replace('\n', '\n\t')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 62: ordinal not in range(128)

Process finished with exit code -2146234327

**Comment by caseysmithpgh** [comment]
CPDB is not working as a part of the PublishToAGOL script because I attempted to add it when we last published in april 2023, but never got it to work.
Currently: I have added the appropriate paths and variables to the script/ini, as well as created a blank mxd in what I believe is the appropriate folder. Some other factor must be missing. It would be worth having a conversation with @croswell81 so that I could ensure all the boxes are checked for it to work.

**Comment by croswell81** [comment]
Script failed uploading MapPLUTO 23v1.2

C:\Python27\ArcGIS10.6\python.exe G:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py
G:\ScheduleTasks\PublishToAGOL\_MapPluto\mappluto.mxd
G:\Connections\arcsdegis\sde@GISPROD.sde\GISPROD.SDE.MapPLUTO
856903: maxRecordCount
creating xml file for MAPPLUTO
Traceback (most recent call last):
  File "G:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py", line 65, in <module>
    mxd.save()
  File "C:\Program Files (x86)\ArcGIS\Desktop10.6\ArcPy\arcpy\utils.py", line 182, in fn_
    return fn(*args, **kw)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.6\ArcPy\arcpy\_mapping.py", line 852, in save
    return convertArcObjectToPythonObject(self._arc_object.save(*gp_fixargs((), True)))
IOError: MapDocObject: Unable to save.  Check to make sure you have write access to the specified file and that there is enough space on the storage device to hold your document.

Process finished with exit code 1

**Comment by caseysmithpgh** [comment]
After reviewing the settings.ini after a second script failure, it was apparent that the ini was left with mid-script failure remains, rather than the variables needed to initiate the process. 

archive/settings_current_as_of_202304.ini was used to overwrite settings.ini and is set for retrying the script.
