### ISSUE TITLE
February Open Data updates

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#866]
## Monthly Notifications:
- [x] Send Zoning reminder email (Run *Monthly_Zoning_Notification_Email.py* -or- use email template) 
- [x] Send TRD reminder email - (Run *Monthly_TRD_Notification_Email.py* -or- use email template) 

## Monthly Datasets

- [x] **Zoning & Sidewalk Cafe features [fgdb/shp]** & **Georeferenced NYC Zoning Maps [fgdb]** 
  - [x] Run Zoning NYSP Dissolve
  - [x] Process Files - Run  *Zoning and Sidewalk Cafe* tool (update metadata, package files for webteam)
  - [x] Manually copy current month's zoning folder from C/temp to BytesProduction folder
  - [x] Manually generate metadata pdfs
  - [x] Check to see if any zoning map changes are in BX CD10 or Staten Island **(If yes, need to run LDGMA)**
  - [x] Upload zoning files to Digital Ocean (jump to ZTLDB generation, and complete QA)
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following two steps need to be scheduled but can be run independently from previous steps**
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoning.py* (Check ini for SDE connection)
  - [ ] ~~Pull data from TRD and update SDE PROD - Run *CopyZoningGeoMaps* script for Zoning Maps only (Check ini for SDE connection)~~
----

- [x] **Zoning Tax Lot Database (ZTLDB) [csv]**

  - [x] Upload/confirm Zoning Features & DOF/DTM Features to Digital Ocean
  - [x] Run dataloading and build issues in github to generate ZTLDB
  - [x] Notify reviewer that ZTLDB is ready for QA
  - [x] Perform QA review of ZTLDB
  - [x] Updated Readme doc and create pdf
  - [x] Receive notification from reviewer that csv and readme are QA'd and ready
  - [x] Zip the csv and pdf readme
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
-----

- [x] **Digital City Map (DCM) [shp/fgdb]**

  - [x] Pull data from TRD and update BytesProduction - Run *DCM_BP_Distribution.py* script
  - [x] Manually generate metadata pdfs
  - [x] Upload files to Digital Ocean
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following step needs to be scheduled but can be run independently from previous steps**
  - [x] Pull data from TRD and update PROD SDE and M lyr meta - Run *DCM_SDE_Distribution.py* script (Check ini for SDE connection)
-----

- [x] **E-Designation [shp/csv]**<sup id="a1"> [1](#f1)</sup>

  - [x] Receive automated email verifying new E-Designation file from Susan has been moved to M drive w/ appended "as of date" from the email and that both *EDes_GPull.py* and *EDes_Generation.py* script (creates shapefile) has been run. *This is currently automated*
        -This can be sent multiple times per month (uses latest one) 
  - [x] Distribute Files - Run  *EDes_BP_Distribution.py* script (update metadata, push files to BytesProduction, package files for webteam) 
  - [x] Manually generate metadata pdf
  - [x] Create web folder in BytesProduction and zip files for CSV and SHP
  - [x] Distribute Files - Run *EDes_SDE_Distribution.py* script (push to SDE PROD, update lyr metadata)
  - [x] Upload files to Digital Ocean
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log 
  - [ ] Update The Guide card (optional)
-----

- [x] **Mandatory Inclusionary Housing (MIH) [shp]**<sup id="a2"> [2](#f2)</sup>

  - [x] Manually edit/create new mapped areas based on Appendix F changes from Paul Power
        -This can happen twice a month (check Stated Meeting Report) 
  - [x] Process Files - Run *BYTES_Distribution* script (update metadata, package files for webteam, push to BytesProduction)
  - [x] Manually generate metadata pdf
  - [x] Upload files to Digital Ocean
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following needs to be scheduled but can be run independently from previous steps**
  - [x] Process Files - Run  *SDE_Distribution* script (push to SDE PROD, update lyr metadata, update & send MIH blocks to DOB) (Check ini for SDE connection)
----

- [x] **Zoning Application Portal (ZAP) [csv]**

  - [x]  Pull Files from Digital Ocean - Run zap_pull.py
  - [x]  Manually update data dictionary (version/update date)
  - [x]  Run zap_package.py
  - [x]  Manually copy files to M:\GIS\DATA\ZAP (ensure to select read-only in properties)
  - [x]  Update Open Data log
  - [x]  Update Bytes (send email to Webteam)
  - [x]  Send email to Open Data team (after confirmation from webteam)
  - [x]  Update MMR log
  - [ ]  Update The Guide card (optional)
----

- [ ] **MapPLUTO [shp/fgdb/csv]**

  - [ ] Receive pluto.csv (corrections included) file from Data Engineering
  - [ ] Receive notification from Lynn that raw_data files have been reviewed and are available. 
  - [ ] Receive and review Data dictionary, Readme and PLUTOChangeReadme
  - [ ] Generate Files - Run *MapPLUTO_BP* script (package files for webteam, moves to Bytes Production)
  - [ ] Distribute Files - Run *MapPLUTO_Distribute* script (push to PROD and ARCHIVE SDEs, updates lyr metadata [MapPLUTO / Archive MapPLUTO / Borough MapPLUTO], creates AGO feature class on PROD) (Check ini for SDE connection)
  - [ ] Manually generate metadata fgdb pdf
  - [ ] Upload to Digital Ocean
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----

- [ ] **Lower Density Growth Management Area (LDGMA) [shp]**<sup id="a3"> [3](#f3)</sup>

  - [ ] Check Zoning Districts for changes in SI/BX10 for month
  - [ ] Generate LDGMA File - Run  *LDGMA_Distribution* script (update metadata, package files for webteam, push to SDE PROD, update lyr metadata)
  _Update script - separate file generation from SDE/lyr meta update (potential for new script for all monthly SDE/lyr meta updates_
  - [ ] Upload files to Digital Ocean
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Quarterly Datasets

- [ ] **LION & Districts ({version}, e.g. 21C) [shp/fgdb]**

  - [ ] Receive notification from GRU that GSS LION toolbox script has been run and files available for web team
  - [ ] Schedule CopyDistricts.py to distribute LION and Districts files across SDE (Check ini for SDE connection)
  - [ ] Receive notification from Web team that all LION and Districts related data sets have been posted to BYTES
  - [ ] Run LION/Districts archive script to archive old version on SDE Archive
  - [ ] Update Open Data log
  - [ ] Upload files to Digital Ocean
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

----
- [ ] **Pseudo Lots (22C) [shp]**
  - [ ] Receive notification from GRU that Pseudo Lots shapefile is available
  - [ ] Update metadata
  - [ ] Update data dictionary
  - [ ] Package/zip files
  - [ ] Distribute files to SDE
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Biannual Datasets

- [ ] **Housing Database [shp/fgdb/csv]**

  - [ ] Receive notification from HED/DE that raw data is available
  - [ ] Run process, package and distribute scripts
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Non-Scheduled Datasets
- [ ] **Capital Projects Database (CPDB) [shp/csv]**

 - [ ] Confirm DO latest folder contains correct version
  - [ ] Run CPDB Bytes Production Distribution Script
  - [ ] Update Data Dictionary and Readme
  - [ ] Run CPDB SDE Distribution Script
  - [ ] Update Open Data Log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
----
- [ ] **Facilities (FacDB) [shp/fgdb/csv]**

  - [ ] Update data and package zips in BytesProduction
  - [ ] Manually distribute to SDE PROD
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean 
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **Waterfront Property Access Areas (WPAA) [shp/fgdb]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **City Owned & Leased Properties (COLP) [shp/fgdb/csv/xlsx]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update SDE PROD (manually)
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **Privately-Owned Public Spaces (POPS) [shp/csv]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **FRESH [shp]**

  - [ ] Receive updated data 
    - [ ] EDC: new discretionary tax incentive census tracts or,
    - [ ] DCP: new zoning text map changes
  - [ ] Update data and package zip file in BytesProduction
  - [ ] Update SDE Prod
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----

## Footnotes
<b id="f1">1:</b> If EARD provides designations for month. [↩](#a1)

<b id="f2">2:</b> If MIH issued by City Council for month. [↩](#a2)

<b id="f3">3:</b> If Zoning District changes in SI/BX10 for month. [↩](#a3)

**\*** clicking icons will navigate user back to original line of footnote

**Comment by jackrosacker** [comment]
> EDes_Generation.py run error: 
...
Traceback Info:
  File "g:/SCRIPTS/EDesignations/scripts/EDes_Generation.py", line 96, in \<module>
    'ULURP_NUM', 'ZONING_MAP', 'DESCRIPTION', 'BBL'])

I mis-read the documentation @caseysmithpgh @croswell81. This script needs to be run with python 3. I ran it with python 2 the first time, causing the pandas error 🤦

**Comment by caseysmithpgh** [comment]
ZTLDB data loading issue, see [here](https://github.com/NYCPlanning/db-zoningtaxlots/issues/130)

**Comment by croswell81** [comment]
MIH corrected to remove extra fields, recalculate shape length geom, and clean metadata (remove geoprocessing), then re-zipped.

SDE distribution script fails to schedule. Was manually copied to SDE for AGO upload. Will revisit script for troubleshoooting.

**Comment by croswell81** [comment]
Jack was able to fix MIH SDE distribution script. @jackrosacker please add any relevant details

**Comment by jackrosacker** [comment]
Task Scheduler appeared to be erroring on how the MIH Distribution script was calling it's own path. The fix was to:
- Call the fully qualified script name via a batch file ([trigger_SDE_Distribution.bat](G:\SCRIPTS\MIH_Distribution\script\))
- (planned) call the file location correctly in the script (see gis-mih issue [#3](https://github.com/NYCPlanning/gis-mih/issues/3#issue-1634643781). Current syntax will define the script location differently depending on whether it is executed from IDE or Task Scheduler. Batch call ignores this difference, but the underlying issue remains in the script
- Moved the `log.write('StartTime')` clause to the beginning of the primary "try" block to provide more process transparency when troubleshooting in the future (previously, script was beginning and failing before it had gotten to any log.write statements, making it look like the script wasn't running at all)
