### ISSUE TITLE
Review SDE Upgrade w/ OTI: share DCP plan, get OTI SDE info etc.

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#885]
- [ ] What OTI SDEs do we interact with (read/write)
- [ ] What is the current version of those SDEs
- [ ] What is their upgrade timeline (if any)
---
- [ ] Get firm timeline from OTI on re-compiling CSCL maintenance application
- [ ] Determine how important it is for OTI and GRU Desktop clients to be at the same release level
- [ ] Do any of the above influence the timeline or upgrade sequence as defined currently

**Comment by jackrosacker** [comment]
Can happen after GRU meeting. We may get most info we need from GRU, and can simply send a courtesy timeline to OTI afterwards, with the option to confirm any items then as well

**Comment by croswell81** [comment]
Did not meet w/ OTI, but was able successfully upgrade SDE. Rodrigo provided info needed.
