### ISSUE TITLE
Build: DTM Processing 

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#891]
### Initial Prompt
1. Pull items from latest DOF GBD
2. Check Geom (tax lots)
   - if _________
   - then run repair geom
3. tax block -> centroids
4. rename export as shp, zip

### Work Steps
- [x] write script
- [x] run tests
- [x] shift script to production environment
  - [x] **remove clause that deletes `\digital_ocean` staging directory**
  - [x] re-name script (currently dev.py)
  - [x] update ini to include prod values
  - [x] git pull to G:\Scripts location
  - [x] Add to documentation
  - [x] Write Readme
- [ ] nice-to-haves
  - [ ] create tests
    - Compare record count between raw feature class and repaired shapefile
  - [ ] ...

**Comment by caseysmithpgh** [comment]
Ran Check Geometry tool test on 3/31/23 tax lots. 

Results:
Repaired version: 16 records were outputted in check geometry dbf (mostly null geometries) 
Original version: 427 records were outputted in check geometry dbf (mostly self intersections)

**Comment by jackrosacker** [comment]
Step: Manual run of `Check Geometry` GP tool on 4/14/23 Tax_Lot_Polygon fc
Result: 
* 427 issues
  * Most: self intersections
  * A handful: null geometry
  * Only one: **could not find spatial index**

Step: Manual run of `Add Index` GP tool on a copy of Tax_Lot_Polygon fc
Result:
* 426 issues remain --> eliminated 'could not find spatial index'

---
Spoke to Damon to verify a few things:
* ZTLDB build fails on a step in which gdal is setting CRS from EPSG 2263 to EPSG 4326
* GIS Team could possibly add changing CRS to our pipeline, but preference is to not --> keeps process in line with other data flows from GIS -> DE
* No need to create spatial index, unless it's required to keep build from breaking --> DE will create one later in the build if necessary

---
Next steps:
* compare check geom results between a version that works and one that definitely doesn't --> does the one that works also contain geom errors? do these results help us understand which error types are accepted by the build process vs which ones break the build?
* test using geopandas / fiona to run geom test and fix and possibly to set CRS as test (I think geopandas uses gdal under the hood to  set CRS, so possible way to test the step that fails during build)
* if not geopandas, use arcpy to repair geom, and save report to file if possible for later review

**Comment by jackrosacker** [comment]
Step: Manual run of `Check Geom` on 2021-01-01 version of Tax_Lot_Polygon
Result:
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63c70f3233c7931e09b40a81/919aa3d2-cbc6-4759-a148-3dac26096d5d)
* Still had 403 geometry errors (vs 427 from 2023-04-14 dataset)
* Same error types, except for spatial index error
* **2021-01-01 fc had spatial index, 2023-04-14 does not**
  * does this have implications for success of ZTLDB build?

**Comment by jackrosacker** [comment]
Script completed. Will be interesting to have @caseysmithpgh run during next open data cycle to check clarity of process.

Script can be executed from the G drive [here](G:\SCRIPTS\gis-dof-dtm) and can be found on Github [here](https://github.com/NYCPlanning/gis-dof-dtm).

Open Data Cycle documentation has been updated to reference scripted process.
