### ISSUE TITLE
Planning Support Type II project expansion

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#892]
- Review Housing DB/MOEC Env. Review joined dataset
- See if projects fall within geographic areas of exclusion (see step 2 [list](https://gcc02.safelinks.protection.outlook.com/ap/p-59584e83/?url=https%3A%2F%2Fnyco365.sharepoint.com%2F%3Ap%3A%2Fr%2Fsites%2FNYCPLANNING%2Fps%2FShared%2520Documents%2FProcess%2520Improvement%2520Workstream%2FProject%2520Management%2FGSB%2520Initiatives%2FExpand%2520Type%2520II%2520List%2F2023.03.28%2520-%2520Type%2520II%2520Research%2520Proposal.pptx%3Fd%3Dw90d8ceddab6646c69995a55342cccad6%26csf%3D1%26web%3D1%26e%3DMhLSsf&data=05%7C01%7CMCROSWE%40planning.nyc.gov%7Ce3d4dbe89b0a4251716c08db34554d7f%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638161313191498938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=osYKzIw7somChOdPJPjp%2B3LqFPD5OhFkK0y53Rfzinw%3D&reserved=0) on slide 2)

**Comment by AmandaDoyle** [comment]
Closing based on SE's email from April 19.  The idea that SE had is not feasible and he does not need GIS' help anymore as of now.
