### ISSUE TITLE
Maintenance: Create network graph of source data -> data product

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#893]
Develop a network graph of all source data to data product, starting with core data products: PLUTO, CPDB, FacDB, DevDB 
Goal - have solid framework for creating a network graph that can be replicated for other data products.

**Comment by fvankrieken** [comment]
Also an issue in data library for this

https://github.com/NYCPlanning/db-data-library/issues/382

**Comment by AmandaDoyle** [comment]
Cleaning up code.  Good for now as first draft.  Review soon and revisit later date if we want to do anything else with it, change, or expand.
