### ISSUE TITLE
Adult Use follow up

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#897]
- [x] Buffer mixed-use lots in buffer and permitted zones to determine how many of the 1,703 lots remain
  - [x] See if any of the 5,009 lots eliminated from review were sensitive receptors [2 Lots - HOW]
      - [x] Buffer 2 lots to determine how many of the 1,703 lots remain
  - [x] Clip permitted lots (1,703 lots ) by combining two buffers above
      - 1,275 lots remain (removed < 5k sf and no street frontage)
      - 600 lots remain that are not in M2 or M3 districts (bookstores)
  - [x] Rerun proximity matrix (w/ DE) on new allowed lots - filtered down from both steps above
      - 209 lots best case / 113 (w/o M2 & M3)
      - 204 lots worst case / 110 (w/o M2 & M3)
  - [x] Reach out to DOF for non-profit exemption list (religious tax exemption)
      - [ ] ~~Cross reference (join) to 1,427 + 82 mixed use lots~~
      - [ ] ~~Buffer cross referenced/joined lots to determine how many of the 1,703 lots remain~~

**Comment by croswell81** [comment]
I buffered all 1,509 mixed use building code lots located in the buffer or permitted zones. 

- This would eliminate 506 lots of 1,703 permitted lots – leaving 1,197 lots remaining. 
  - Of the 506 lots eliminated, 140 are only partially eliminated

There were two lots part of the DCP review that were eliminated/disqualified as sensitive receptors – both were houses of worship

- When buffered 500 feet:
  - This would eliminate 24 total lots (18 additional*) of 1,703 permitted lots (*6 lots were the same as the 506 above)
  - Of the 24 lots eliminated, 15 are only partially eliminated

**Comment by croswell81** [comment]
Dept. of Law requested re-run of matrix (proximity model) on 4/18/23. Amanda set up meeting between DE & GIS for 4/25 to train GIS on running [script](proximity-constrained siting). Will send results to Law when available.

Still have not heard back from DOF/Tom Dick about non-profit exemption list. Last email from Tom Dick on 4/11.

**Comment by damonmcc** [comment]
relevant repo with DE's old script: [NYCPlanning/aue](https://github.com/NYCPlanning/aue)

**Comment by AmandaDoyle** [comment]
DE project
Rerun [proximity-constrained siting analysis](https://medium.com/nyc-planning-digital/proximity-constrained-siting-ddc7b4fa03dc) for GIS team.
Goals: 1) Share new outputs with GIS team by April 28 2) teach GIS team how to run scripts

**Comment by damonmcc** [comment]
reran and shared outputs with GIS

**Comment by damonmcc** [comment]
with new input data which excluded lots in M2 and M3 zones, reran and shared with GIS yesterday

**Comment by croswell81** [comment]
Law Dept. requested run proximity analysis for bookstore sitings, which excludes M2 & M3 districts. 

More than half of the lots are in M2 and M3 lots, 675 of 1,275 (53%)

Data Engineering reran without M2/M3 zoned lots:
    - The best case scenario (most establishments sited) is 113, and there are nine permutations (combos) that allow this. Previously was 151 and 4 combos.
    - The worst case scenario (least establishments sited) is 110, and there are 20 permutations (combos) that allow this. Previously was 147 and 29 combos.

**Comment by croswell81** [comment]
4/28/23 - Law Dept. wanted to know breakdown of following lot counts between Manhattan and outer boroughs

Category                                                                    # in Manhattan                          # in Outer Boroughs
1,509 mixed use building code lots
Identified in para. 13 of the 2nd Stip                                   360                                                1,149

1,275 lots remaining after “buffering”
 where AE could be located                                                   10                                                1,265                     
204 lots available for AE “if AE were
located in these lots”                                                               5                                                  199
