### ISSUE TITLE
J: MapPLUTO (test)

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#9]
Test version of MapPLUTO using PTS rather than RPAD. Will create 19v1 once the final roll is released.

**Comment by AmandaDoyle** [comment]
Project repo: https://github.com/NYCPlanning/db-pluto

**Comment by AmandaDoyle** [comment]
- spent much of the time working to properly load PTS data into PostgreSQL
- mapped PTS fields to RPAD and CAMA fields so that downstream scripts work
- updated code to work with PTS values (i.e. no longer need to convert day of year and year format to MM/DD/YYYY)
