### ISSUE TITLE
Publish: FacDB & POPS 

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#900]
### FacDB
- [x] Research + understand previous workflows
- [x] Commit to Github
- [x] Process latest data set (either manual or scripted)
  - [x] Extract - from Github
  - [x] Transform - update schema, metadata, etc.
    - [x] Export fc to csv + shp
    - [x] Transfer metadata from June 2022 fc to current output fc
      - check for and update dates etc.
      - check for and remove sensitive info
    - [x] Manually transfer updated metadata to shp
      - Data Dict + Readme: will be addressed by Lynn/Amanda and delivered by Matt
      - Skip **raw_data** and **archive** folders when building Bytes folder
  - [x] Load - SDE, AGO, BytesProduction (where else?)
- [x] Update documentation - Zenhub, README etc.
- [ ] Create issues for non-urgent follow up items 

### POPS
Shapefile:
- [x] Compare previous releases and update schema (see final list in comments below)
- [x] Plot latest POPS data from dcp_pops_20230320.csv (from digital ocean)
- [x] Export out as feature class (edit version)
- [x] Change field names in ArcGIS Pro
- [x] Export out cuts of feature class with schema fields in correct order
- [x] Join feature classes together to have one feature class with all schema in correct order
- [x] Calculate 'nta' field by spatially joining POPS to 2020 Neighborhood Tabulation Area (NTA).lyr, use NTAName field
- [x] Calcualte 'cc_dist' field by spatially joining POPS to NYC Council Districts (22C) layer, use CounDist field
- [x] Export to shapefile, name nycpops_20230505
- [x] Import metadata from previous version of pops (nycpops_20210811)
- [x] Update publish date - 5/5/2023 and creation data 3/20/2023

CSV:
- [x] Upload dcp_pops_20230320.csv to file geodatabase table
- [x] Upload nycpops_20230505 shapefile to file geodatabase table (only need popsnumber, cc_dist, and nta fields)
- [x] Join two tables together on popsnumber field
- [x] Calculate 'council_district' from cc_dist field
- [x] Calculate 'nta' fields from nta field
- [x] Export out new csv nycpops_20230430.csv

Zip files:
- [x] Update nycpops_datadictionary.xlsx
- [x] Check/compare pops match facilities database records and values (cc_dist / nta)
- [x] Zip up csv and data dictionary into nycpops_20230430csv.zip
- [x] Zip up shp and data dictionary into nycpops_20230430shp.zip

**Comment by jackrosacker** [comment]
Let me know how I can help support these datasets. Maybe we can catch up on this tomorrow

**Comment by caseysmithpgh** [comment]
@jackrosacker sounds good. I don't see a response from Kiyoshi or Jose yet--so I'm going to dig into what documentation we have on these datasets now so that I can get a better scope of all that's involved

**Comment by caseysmithpgh** [comment]
Existing issue for fixing POPS Script #844

**Comment by caseysmithpgh** [comment]
POPS script ran with a few minor configurations, documenting changes in #844

Script published to SDE-- as a safety net I did create a copy of the previously published version of MH_POPS on the SDE -- can be deleted after @croswell81 confirms that MH_POPS looks clean. 

Likely going to re-run after some edits are made because the current zipping configs in the script are not publishing them to the web folder and are also creating a yucky nested zip (ie. output.zip\GIS\BytesProduction\POPS\YYYY\version\...)

**Comment by croswell81** [comment]
![image.png](https://images.zenhubusercontent.com/5ce2f81ac6ec005d8883f4f2/15274782-25ba-4a19-9a3f-a16aaf7f44ad)

**Comment by croswell81** [comment]
Final Schema for POPS 2023:

![image.png](https://images.zenhubusercontent.com/5ce2f81ac6ec005d8883f4f2/39cb8737-33d3-4e4f-a424-a8418103d327)

**Comment by jackrosacker** [comment]
@croswell81 [FacDB metadata is ready for your review](M:\GIS\BytesProduction\FacilitiesDB\20230430). Currently resides on the shapefile and feature class

**Comment by croswell81** [comment]
All required zip files, metadata, readmes, and data dictionaries were updated and packaged. Both web folders for facilities and POPS are final on **M:\GIS\BytesProduction**

**Comment by croswell81** [comment]
@jackrosacker Do any of the unchecked items need to be checked? Would like to close this out this sprint.

**Comment by jackrosacker** [comment]
@croswell81 we should be extremely close. I would probably just need to confirm that FacDB is up on AGO, and if not, the method to get it there
