### ISSUE TITLE
Project: Proximity-constrained siting analysis for GIS team

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#904]
Rerun [proximity-constrained siting analysis](https://medium.com/nyc-planning-digital/proximity-constrained-siting-ddc7b4fa03dc) for GIS team.
Goals: 1) Share new outputs with GIS team 2) teach GIS team how to run scripts

**Comment by damonmcc** [comment]
@AmandaDoyle 
here's the existing issue Matt made https://github.com/NYCPlanning/edm-overview/issues/897

**Comment by AmandaDoyle** [comment]
Closing issue because it's duplicative
