### ISSUE TITLE
April Open Data updates

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#907]
## Monthly Notifications:
- [x] Send Zoning reminder email (Run *Monthly_Zoning_Notification_Email.py* -or- use email template) 
- [x] Send TRD reminder email - (Run *Monthly_TRD_Notification_Email.py* -or- use email template) 

## Monthly Datasets

- [x] **Zoning & Sidewalk Cafe features [fgdb/shp]** & **Georeferenced NYC Zoning Maps [fgdb]** 
  - [x] Run Zoning NYSP Dissolve
  - [x] Process Files - Run  *Zoning and Sidewalk Cafe* tool (update metadata, package files for webteam)
  - [x] Manually copy current month's zoning folder from C/temp to BytesProduction folder
  - [x] Manually generate metadata pdfs
  - [x] Check to see if any zoning map changes are in BX CD10 or Staten Island **(If yes, need to run [LDGMA](#a3))**
  - [x] Upload zoning files to Digital Ocean (jump to ZTLDB generation, and complete QA)
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following can be scheduled after ZTLDB QA is complete, but can be run independently from previous steps**
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoning.py* (Check ini for SDE connection)
  - [ ] ~~Pull data from TRD and update SDE PROD - Run *CopyZoningGeoMaps* script for Zoning Maps only (Check ini for SDE connection)~~ _Replaced by AGO publishing scripts. Retaining for future review_
----

- [x] **Zoning Tax Lot Database (ZTLDB) [csv]**

  - [x] Prepare DOF/DTM data and publish to Digital Ocean
  - [x] Confirm correct Zoning Features & DOF/DTM in Digital Ocean
  - [x] Run dataloading and build issues in github to generate ZTLDB
  - [x] Perform QA review of ZTLDB
  - [x] Updated Readme doc and create pdf
  - [x] Zip the csv and pdf readme
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Update Bytes (send email to Webteam)
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
-----

- [x] **Digital City Map (DCM) [shp/fgdb]**

  - [x] Pull data from TRD and update BytesProduction - Run *DCM_BP_Distribution.py* script
  - [x] Manually generate metadata pdfs
  - [x] Update Open Data log
  
  ***Checkpoint***

  - [x] Pull data from TRD and update PROD SDE and M lyr meta - Run *DCM_SDE_Distribution.py* script (Check ini for SDE connection)
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

-----

- [x] **E-Designation [shp/csv]**<sup id="a1"> [1](#f1)</sup>

  - [x] Receive automated email verifying new E-Designation file from Susan has been moved to M drive w/ appended "as of date" from the email and that both *EDes_GPull.py* and *EDes_Generation.py* script (creates shapefile) has been run. *This is currently automated*
        -This can be sent multiple times per month (uses latest one) 
  - [x] Distribute Files - Run  *EDes_BP_Distribution.py* script (update metadata, push files to BytesProduction, package files for webteam) 
  - [x] Manually generate metadata pdf
  - [x] Create web folder in BytesProduction and zip files for CSV and SHP
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Distribute Files - Run *EDes_SDE_Distribution.py* script (push to SDE PROD, update lyr metadata)
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log 
  - [ ] Update The Guide card (optional)
-----

- [ ] **Mandatory Inclusionary Housing (MIH) [shp]**<sup id="a2"> [2](#f2)</sup>
  - [ ] :star: Included in this cycle :star:
  - [ ] Manually edit/create new mapped areas based on Appendix F changes from Paul Power
        -This can happen twice a month (check Stated Meeting Report) 
  - [ ] Process Files - Run *BYTES_Distribution* script (update metadata, package files for webteam, push to BytesProduction)
  - [ ] Manually generate metadata pdf
  - [ ] Update Open Data log
  
  ***Checkpoint***
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following needs to be scheduled but can be run independently from previous steps**
  - [ ] Process Files - Run  *SDE_Distribution* script (push to SDE PROD, update lyr metadata, update & send MIH blocks to DOB) (Check ini for SDE connection)
----

- [x] **Zoning Application Portal (ZAP) [csv]**

  - [x]  Pull Files from Digital Ocean - Run zap_pull.py
  - [x]  Manually update data dictionary (version/update date)
  - [x]  Run zap_package.py
  - [x]  Manually copy files to M:\GIS\DATA\ZAP (ensure to select read-only in properties)
  - [x]  Update Open Data log
  
  ***Checkpoint***
  - [x]  Update Bytes (send email to Webteam)
  - [x]  Send email to Open Data team (after confirmation from webteam)
  - [x]  Update MMR log
  - [ ]  Update The Guide card (optional)
----

- [ ] **MapPLUTO [shp/fgdb/csv]**
  - [x] :star: Included in this cycle :star:
  - [x] Receive pluto.csv (corrections included) file from Data Engineering
  - [x] Receive notification from Lynn that raw_data files have been reviewed and are available. 
  - [x] Receive and review Data dictionary, Readme and PLUTOChangeReadme
  - [x] Generate Files - Run *MapPLUTO_BP* script (package files for webteam, moves to Bytes Production)
  - [x] Manually generate metadata fgdb pdf
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Distribute Files - Run *MapPLUTO_Distribute* script (push to PROD and ARCHIVE SDEs, updates lyr metadata [MapPLUTO / Archive MapPLUTO / Borough MapPLUTO], creates AGO feature class on PROD) (Check ini for SDE connection)
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
----

- [ ] **Lower Density Growth Management Area (LDGMA) [shp]**<sup id="a3"> [3](#f3)</sup>
  - [ ] :star: Included in this cycle :star:
  - [ ] Check Zoning Districts for changes in SI/BX10 for month
  - [ ] Generate LDGMA File - Run  *LDGMA_Distribution* script (update metadata, package files for webteam, push to SDE PROD, update lyr metadata)
  _Update script - separate file generation from SDE/lyr meta update (potential for new script for all monthly SDE/lyr meta updates_
  - [ ] Update Open Data log

  ***Checkpoint***
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Quarterly Datasets

- [ ] **LION & Districts ({version}, e.g. 21C) [shp/fgdb]**
  - [x] :star: Included in this cycle :star:
  - [x] Receive notification from GRU that GSS LION toolbox script has been run and files available for web team
  - [x] Update Open Data log
  - [ ] Schedule CopyDistricts.py to distribute LION and Districts files across SDE (Check ini for SDE connection)
  - [ ] Source M:/ PUMA 2020 layers 
  - [x] Receive notification from Web team that all LION and Districts related data sets have been posted to BYTES
  - [ ] Run LION/Districts archive script to archive old version on SDE Archive
  - [ ] Update AGOL 
  - [ ] Upload files to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

----
- [x] **Pseudo Lots (22C) [shp]**
  - [x] :star: Included in this cycle :star:
  - [x] Receive notification from GRU that Pseudo Lots shapefile is available
  - [x] Update metadata
  - [x] Update data dictionary
  - [x] Package/zip files
  - [x] Update Open Data log
  - [x] Distribute files to SDE
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

## Biannual Datasets

- [ ] **Housing Database [shp/fgdb/csv]**
  - [x] :star: Included in this cycle :star:
  - [ ] Receive notification from HED/DE that raw data is available
  - [ ] Run process, package and distribute scripts
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Non-Scheduled Datasets
- [ ] **Capital Projects Database (CPDB) [shp/csv]**
  - [ ] :star: Included in this cycle :star:
  - [ ] Confirm DO latest folder contains correct version
  - [ ] Run CPDB Bytes Production Distribution Script
  - [ ] Update Data Dictionary and Readme
  - [ ] Update Open Data Log
  - [ ] Run CPDB SDE Distribution Script
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
----
- [x] **Facilities (FacDB) [shp/fgdb/csv]**
  - [x] :star: Included in this cycle :star:
  - [x] Update data and package zips in BytesProduction
  - [x] Update Open Data log
  - [x] Manually distribute to SDE PROD
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean 
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [x] **Privately-Owned Public Spaces (POPS) [shp/csv]**
  - [x] :star: Included in this cycle :star:
  - [x] Update M: drive directory to include these files
  - [x] Update Open Data log
  - [x] Manually distribute to SDE PROD
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **Waterfront Property Access Areas (WPAA) [shp/fgdb]**
  - [ ] :star: Included in this cycle :star:
  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **City Owned & Leased Properties (COLP) [shp/fgdb/csv/xlsx]**
  - [x] :star: Included in this cycle :star:
  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update SDE PROD (manually)
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **FRESH [shp]**
  - [ ] :star: Included in this cycle :star:
  - [ ] Receive updated data 
    - [ ] EDC: new discretionary tax incentive census tracts or,
    - [ ] DCP: new zoning text map changes
  - [ ] Update data and package zip file in BytesProduction
  - [ ] Update SDE Prod
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----

## Footnotes
<b id="f1">1:</b> If EARD provides designations for month. [↩](#a1)

<b id="f2">2:</b> If MIH issued by City Council for month. [↩](#a2)

<b id="f3">3:</b> If Zoning District changes in SI/BX10 for month. [↩](#a3)

**\*** clicking icons will navigate user back to original line of footnote

**Comment by jackrosacker** [comment]
Amanda confirmed that PLUTO minor is expected to be published this cycle

**Comment by jackrosacker** [comment]
Added special file naming and output convention changes to task list based on review of the Web Team process. Includes DCM product naming convention, MapPLUTO metadata publication changes, and georeferenced zoning map naming conventions.

All are due to conversations with Mary and Web Team in which it was discovered that various products are renamed behind the scenes by Web Team between GIS delivery and Bytes hosting steps. These proposed changes on GIS side would minimize changes required of Web Team.

Follow up will be needed for short term and long term process review.

**Comment by jackrosacker** [comment]
ZTLDB build is failing, tracking collaborative troublshooting with DE in issue [#134](https://github.com/NYCPlanning/db-zoningtaxlots/issues/134)

**Comment by jackrosacker** [comment]
@casey solved the [ZTLDB dataloading/build issue](https://github.com/NYCPlanning/db-zoningtaxlots/issues/134)! Turns out it is crucial to run Repair Geometry on the shapefile _after is has been exported from the feature class_, rather than running Repair Geometry on the feature class before it has been exported to shapefile

**Comment by jackrosacker** [comment]
Waiting on COLP until (hopefully) this Friday per 5/9 email from Lynn: 
```text
Subject: PLUTO 23v1.1

If GIS has time to do the review of minor PLUTO releases, I'd like to turn it over to you.
DCAS is reviewing COLP. They are supposed to get back to us by Friday.

```
