### ISSUE TITLE
Update: CEQR Air update for major contributors

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#909]
Update DEC State Facility Air Permit Records and DEC Title V Air Permit Records data, which is available for download [here](https://www.ceqr.app/data/air-quality).

To get the geographic information and source we pull Issued State Facility Air Permits from [here](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.ny.gov%2FEnergy-Environment%2FIssued-State-Facility-Air-Permits%2F2wgt-bc53&data=05%7C01%7CADoyle%40planning.nyc.gov%7C17d1228e752847ec9a1008db4675bc7a%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638181243701158142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BaINxQelxDfpRKgFQNLAUvaUc4iypT3jdmxNP3dzkNM%3D&reserved=0) and Issued Title V Facility Permits from [here](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.ny.gov%2FEnergy-Environment%2FIssued-Title-V-Facility-Permits%2F4n3a-en4b&data=05%7C01%7CADoyle%40planning.nyc.gov%7C17d1228e752847ec9a1008db4675bc7a%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638181243701158142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OjagV2pMbxsRd9redoH7dB0KHMhLb%2Bq7eTLQ900GQ0o%3D&reserved=0)

Known things that need to be addressed:
- I kicked off a build for nysdec_title_v_facility_permits, but it [failed]. 
(https://github.com/NYCPlanning/ceqr-app-data/actions/runs/4812561529/jobs/8567962643).  Haven't dug in yet.
- The url needs to be updated for nysdec_state_facility_permits in [script](https://github.com/NYCPlanning/ceqr-app-data/blob/main/recipes/nysdec_state_facility_permits/build.py).

**Comment by damonmcc** [comment]
per chat and code review with @AmandaDoyle

next step:
- send latest staging outputs to ERD for revieew
  - (`nysdec_state_facility_permits.csv` and `nysdec_state_facility_permits_geo_rejects.csv`)
  - files are ready to share, could zip the two primary files along with the raw data and the output as a shapefile
