### ISSUE TITLE
Refactor: FacDB & POPS Distribution

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#913]
See previous POPS script updates issues here: #844

Dependencies: 
Collaborate with DE to produce DO hosted outputs that match our SHP and CSV schema requirements. 

DE Request specifics:
- If desired output location is edm-recipies/pops, we are proposing that DE produce 2 new outputs in this location
      1. CSV with open data schema (to be provided by matt)
      2. SHP with different open data schema (10 characters, not truncated) (to be provided by matt)
- In additions to these outputs being available on DO, matt would find it helpful to have these links available on the db-facilities github repo home page. 

From here we can begin to develop a one stop shop for FacDB and POPS data processing and distribution (to SDE, BytesProduction etc.). These datasets are legally bound to each other in that one cannot be published without the other, so it makes sense to combine their publication/distribution process.

**Comment by caseysmithpgh** [comment]
![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/57bd15d8-6771-452c-9964-8926ca237ae4)

**Comment by jackrosacker** [comment]
> ![image.png](https://camo.githubusercontent.com/bc6ee41d5221337f4cd64760dbab9cfb584855614f19ba31f3eb7e6e83c3a048/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632386365646535643663323539356530326166323636632f35376264313564382d363737312d343532632d393936342d383932366361323337616534)

@caseysmithpgh @croswell81 do either of you have the source sheet for this screenshot?

**Comment by croswell81** [comment]
I'm pretty sure I processed this manually last time and did not run the script. Happy to meet w/ @jackrosacker if it would help to go through what the script should do.

**Comment by jackrosacker** [comment]
Note: these two product processing scripts have been combined into one repo, and have been written to handle DE outputs as-is, and to apply schema updates and file type changes on the GIS side. Future communication with DE to refine their output file types and schemas would still be valuable, and could be easily accommodated for within the GIS team scripts
