### ISSUE TITLE
M: Open Data Issue: REST/GeoJSON Files capped at 2,000 records

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#93]
By default, AGOL only makes the first 2,000 records of a file available (reported for PLUTO).

Will fix for PLUTO and any other datasest w/ more than 2,000 records.

- [x] Fix for MapPluto
- [x] Identify and fix remaining affected AGOL data sets.

**Comment by croswell81** [comment]
@aferrar can you prioritize LION node and LION as the next two datasets to fix. We received another open data request that LION node only returns 2,000 records and can we fix that.
