### ISSUE TITLE
MapPLUTO 23v1.2 QA & processing

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#951]
- [ ] **MapPLUTO [shp/fgdb/csv]**
  - [x] Receive notification that raw data files are available (pluto change files included) from Data Engineering
  - [x] Receive QAQC raw_data files
  - [x] Review and update Data dictionary, Readme and PLUTOChangeReadme
  - [x] Generate Files - Run *MapPLUTO_BP* script (package files for webteam, moves to Bytes Production)
  - [x] Manually generate metadata fgdb pdfs
  - [x] Schedule MapPLUTO_Distribution
  - [x] Update Open Data log
  - [x] Send to webteam for BYTES
  - [x] Upload to Digital Ocean
  - [x] Create ADO ticket and test data
  - [x] Send to Open Data Team

**Comment by croswell81** [comment]
Items to confirm for next MapPLUTO run:

  - [ ] update metadata templates (where are they located???)
  - [ ] confirm files needed and Pluto Change File output
  - [ ] confirm if GIS scripts are using all raw data files or only the pluto.csv
  - [ ] update PLUTO section of the ZenHub open data template

**Comment by caseysmithpgh** [comment]
@croswell81 @jackrosacker 
MapPLUTO Distribution appears to have run successfully over the weekend. Log reflects a ~45 min run, and SDE PROD shows that 23v1.2 is live.

**Comment by jackrosacker** [comment]
That's great! Wonder what was wrong with the run last week.
