### ISSUE TITLE
Update: PFF Decennial DHC data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#956]
Transform excel spreadsheets into format usable by OSE for [Population Fact Finder app](https://popfactfinder.planning.nyc.gov/#11.67/40.7198/-73.9515). 
Goal - deliver updated data to OSE by August 11
Dependent on receiving data from Population
Sync up with @damonmcc because he did dome work on this in the beginning of the year, but I think [this](https://github.com/NYCPlanning/db-factfinder/tree/250-acs-data-update-0610-and-1721) is the right branch with the workflows to transform excel spreadsheets into the format needed for the app.
This is census released 2020 DHC data.  It's sister dataset is the 2010 DHC dataset.  Data Engineering will need to build new  or tweak existing pipelines to incorporate 2020 variables.  Population can help with this project.

**Comment by damonmcc** [comment]
With completion targeted for mid September, we're awaiting an update on the work between the Application Engineering and Design teams before they start to incorporate our new data
