### ISSUE TITLE
Finalize DCP GIS Teams Channel Language

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#967]
[GIS Users Microsoft Teams channel materials](https://nyco365.sharepoint.com/:w:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7B46E7F52F-25A2-4F21-890B-6E78BD7B8441%7D&file=GIS%20Users%20Microsoft%20Teams%20channel%20materials.docx&action=default&mobileredirect=true)

**Comment by croswell81** [comment]
@caseysmithpgh I've reviewed the entire document and made many changes, added some of my own questions and added a few comments.

@AmandaDoyle I think we can meet next week (8/21-8/25)
