### ISSUE TITLE
August 2023 Open Data updates

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#975]
## Monthly Notifications:
- [ ] ~~Send Zoning reminder email (Run *Monthly_Zoning_Notification_Email.py* -or- use email template)~~ _will not send, as no Stated Meetings have occurred since 8/3, the changes from which were incorporated into the July OD publication cycle_ 
- [x] Send TRD reminder email - (Run *Monthly_TRD_Notification_Email.py* -or- use email template) 

## Monthly Datasets

- [x] **Zoning & Sidewalk Cafe features [fgdb/shp]** & **Georeferenced NYC Zoning Maps [fgdb]** 
  - [x] Run Zoning NYSP Dissolve
  - [x] Process Files - Run  *Zoning and Sidewalk Cafe* tool (update metadata, package files for webteam)
  - [x] Manually copy current month's zoning folder from C/temp to BytesProduction folder
  - [x] Manually generate metadata pdfs
  - [ ] ~~Check to see if any zoning map changes are in BX CD10 or Staten Island **(If yes, need to run [LDGMA](#a3))**~~
  - [x] Upload zoning files to Digital Ocean (jump to ZTLDB generation, and complete QA)
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Update Bytes (send email to Webteam)
  - [x] Create ADO Issue
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following can be scheduled after ZTLDB QA is complete, but can be run independently from previous steps**
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoning.py* (Check ini for SDE connection)
  - [ ] ~~Pull data from TRD and update SDE PROD - Run *CopyZoningGeoMaps* script for Zoning Maps only (Check ini for SDE connection)~~ _Replaced by AGO publishing scripts. Retaining for future review_
----

- [x] **Zoning Tax Lot Database (ZTLDB) [csv]**

  - [x] Prepare DOF/DTM data and publish to Digital Ocean
  - [x] Confirm correct Zoning Features & DOF/DTM in Digital Ocean
  - [x] Run dataloading and build issues in github to generate ZTLDB
  - [x] Perform QA review of ZTLDB
  - [x] Updated Readme doc and create pdf
  - [x] Zip the csv and pdf readme
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Update Bytes (send email to Webteam)
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
-----

- [x] **Digital City Map (DCM) [shp/fgdb]**

~~**_2023-09-08 :: On hold pending TRD updates. Expected to be complete by COB today_**~~
**_2023-09-11 :: TRD done, cleared to publish DCM_**
  - [x] Pull data from TRD and update BytesProduction - Run *DCM_BP_Distribution.py* script
  - [x] Manually generate metadata pdfs
  - [x] Update Open Data log
  
  ***Checkpoint***

  - [x] Pull data from TRD and update PROD SDE and M lyr meta - Run *DCM_SDE_Distribution.py* script (Check ini for SDE connection)
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Create ADO Issue
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
-----

- [x] **E-Designation [shp/csv]**<sup id="a1"> [1](#f1)</sup>

~~**_2023-09-08 :: On hold pending release of new E-Des email. Last email was 8/4 which was published during July Cycle_**~~
**_2023-09-13 :: New email received - cleared for GIS Team publication_**
<details open><summary>Reveal TODOs</summary>

  - [x] Receive automated email verifying new E-Designation file from Susan has been moved to M drive w/ appended "as of date" from the email and that both *EDes_GPull.py* and *EDes_Generation.py* script (creates shapefile) has been run. *This is currently automated*
        -This can be sent multiple times per month (uses latest one) 
  - [x] Distribute Files - Run  *EDes_BP_Distribution.py* script (update metadata, push files to BytesProduction, package files for webteam) 
  - [x] Manually generate metadata pdf
  - [x] Create web folder in BytesProduction and zip files for CSV and SHP
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Distribute Files - Run *EDes_SDE_Distribution.py* script (push to SDE PROD, update lyr metadata)
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Create ADO Issue
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log 
  - [ ] Update The Guide card (optional)
</details>

-----

- [ ] **Mandatory Inclusionary Housing (MIH) [shp]**<sup id="a2"> [2](#f2)</sup>
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>

  - [ ] Manually edit/create new mapped areas based on Appendix F changes from Paul Power
        -This can happen twice a month (check Stated Meeting Report) 
  - [ ] Process Files - Run *BYTES_Distribution* script (update metadata, package files for webteam, push to BytesProduction)
  - [ ] Manually generate metadata pdf
  - [ ] Update Open Data log
  
  ***Checkpoint***
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Create ADO Issue
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following needs to be scheduled but can be run independently from previous steps**
  - [ ] Process Files - Run  *SDE_Distribution* script (push to SDE PROD, update lyr metadata, update & send MIH blocks to DOB) (Check ini for SDE connection)
</details>

----

- [x] **Zoning Application Portal (ZAP) [csv]**

  - [x]  Pull Files from Digital Ocean - Run zap_pull.py
  - [x]  Manually update data dictionary (version/update date)
  - [x]  Run zap_package.py
  - [x]  Manually copy files to M:\GIS\DATA\ZAP (ensure to select read-only in properties)
  - [x]  Update Open Data log
  
  ***Checkpoint***
  - [x]  Update Bytes (send email to Webteam)
  - [x]  Send email to Open Data team (after confirmation from webteam)
  - [x]  Update MMR log
  - [ ]  Update The Guide card (optional)
----

- [ ] **MapPLUTO [shp/fgdb/csv]**
  - [x] :star: Included in this cycle :star:
  - [x] Receive confirmation from Data Engineering that latest version of PLUTO is ready on [Digital Ocean](https://cloud.digitalocean.com/spaces/edm-publishing?path=db-pluto%2Fmain%2Flatest%2F)
  - [ ] Perform [QA](https://nyco365.sharepoint.com/sites/NYCPLANNING/itd/edm/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2FShared%20Documents%2FDOCUMENTATION%2FEDM%20Manual%2Epdf&parent=%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2FShared%20Documents%2FDOCUMENTATION&p=true&ga=1)
  - [ ] Review and update metadata: [Data dictionary, Readme, PLUTOChangeReadme](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/Metadata%20for%20review?csf=1&web=1&e=iVrAe9), and if needed: metadata template XMLs
  - [ ] Generate Files - Run *MapPLUTO_BP* script (package files for webteam, moves to Bytes Production)
  - [ ] Manually generate metadata fgdb pdfs
  - [ ] Update Open Data log
  
  ***Checkpoint***
  - [ ] Distribute Files - Run *MapPLUTO_Distribute* script (push to PROD and ARCHIVE SDEs, updates lyr metadata [MapPLUTO / Archive MapPLUTO / Borough MapPLUTO], creates AGO feature class on PROD) (Check ini for SDE connection)
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload to Digital Ocean
  - [ ] Create ADO Issue
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----

- [ ] **Lower Density Growth Management Area (LDGMA) [shp]**<sup id="a3"> [3](#f3)</sup>
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>
  
  - [ ] Check Zoning Districts for changes in SI/BX10 for month
  - [ ] Generate LDGMA File - Run  *LDGMA_Distribution* script (update metadata, package files for webteam, push to SDE PROD, update lyr metadata)
  _Update script - separate file generation from SDE/lyr meta update (potential for new script for all monthly SDE/lyr meta updates_
  - [ ] Update Open Data log

  ***Checkpoint***
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean
  - [ ] Create ADO Issue
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

## Quarterly Datasets

- [ ] **LION & Districts ({version}, e.g. 21C) [shp/fgdb]**
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>

  - [ ] Receive notification from GRU that GSS LION toolbox script has been run and files available for web team
  - [ ] Update Open Data log
  - [ ] Schedule CopyDistricts.py to distribute LION and Districts files across SDE (Check ini for SDE connection)
  - [ ] Receive notification from Web team that all LION and Districts related data sets have been posted to BYTES
  - [ ] Run LION/Districts archive script to archive old version on SDE Archive
  - [ ] Update AGOL 
  - [ ] Upload files to Digital Ocean
  - [ ] Create ADO Issue
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

----
- [ ] **Pseudo Lots (22C) [shp]**
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>
  
  - [ ] Receive notification from GRU that Pseudo Lots shapefile is available
  - [ ] Update metadata
  - [ ] Update data dictionary
  - [ ] Package/zip files
  - [ ] Update Open Data log
  - [ ] Distribute files to SDE
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

## Biannual Datasets

- [ ] **Housing Database [shp/fgdb/csv]**
  - [ ] :star: Included in this cycle :star:
<details open><summary>Reveal TODOs</summary>
  
  - [ ] Receive notification from HED/DE that raw data is available
  - [ ] Run process, package and distribute scripts
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

----
- [x] **Facilities (FacDB) [shp/fgdb/csv]**
  - [x] :star: Included in this cycle :star:
<details open><summary>Reveal TODOs</summary>
  
  - [x] Receive confirmation from Data Engineering that latest version of Facilities is ready on [Digital Ocean](https://edm-publishing.nyc3.digitaloceanspaces.com/db-facilities/main/latest/output)
  - [x] Perform [QA](https://nyco365.sharepoint.com/sites/NYCPLANNING/itd/edm/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2FShared%20Documents%2FDOCUMENTATION%2FEDM%20Manual%2Epdf&parent=%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2FShared%20Documents%2FDOCUMENTATION&p=true&ga=1)
  - [x] Review and update metadata: [Data dictionary, Readme](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/Metadata%20for%20review?csf=1&web=1&e=iVrAe9)
  - [x] Generate Open Data packages - Run *facilities_processing.py* script
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Distribute to SDE PROD
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Create ADO Issue
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

----
- [x] **Privately-Owned Public Spaces (POPS) [shp/csv]**
  - [x] :star: Included in this cycle :star:
<details open><summary>Reveal TODOs</summary>
  
  - [x] Receive confirmation from Data Engineering that latest version of POPS is ready on [Digital Ocean](https://edm-recipes.nyc3.digitaloceanspaces.com/datasets/dcp_pops/latest/)
  - [x] Review and update metadata: [Data dictionary only](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/Metadata%20for%20review?csf=1&web=1&e=iVrAe9)
  - [x] Generate Open Data packages - Run *pops_processing.py* script
  - [x] Update Open Data log
  
  ***Checkpoint***
  - [x] Distribute to SDE PROD  
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Create ADO Issue
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

## Non-Scheduled Datasets
- [ ] **Capital Projects Database (CPDB) [shp/csv]**
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>
  
  - [ ] Confirm DO latest folder contains correct version
  - [ ] Run CPDB Bytes Production Distribution Script
  - [ ] Update Data Dictionary
  - [ ] Update Open Data Log
  - [ ] Run CPDB SDE Distribution Script
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
</details>

----
- [ ] #988
  - [x] :star: Included in this cycle :star:
  <details open><summary>Reveal TODOs</summary>
  
    - [x] Receive notification and emailed zip file from Climate and Sustainability
    - [ ] Update M: drive directory to include these files
    - [ ] Update Open Data log
 
    ***Checkpoint***
    - [ ] Update Bytes (send email to Webteam)
    - [ ] Update AGOL
    - [ ] Upload files to Digital Ocean
    - [ ] Create ADO Issue (?)
    - [ ] Send email to Open Data team (after confirmation from webteam)
    - [ ] Update MMR log
    - [ ] Update The Guide card (optional)
  </details>

----
- [ ] **City Owned & Leased Properties (COLP) [shp/fgdb/csv/xlsx]**
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>
  
  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update SDE PROD (manually)
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

----
- [ ] **FRESH [shp]**
  - [ ] :star: Included in this cycle :star:
<details><summary>Reveal TODOs</summary>
  
  - [ ] Receive updated data 
    - [ ] EDC: new discretionary tax incentive census tracts or,
    - [ ] DCP: new zoning text map changes
  - [ ] Update data and package zip file in BytesProduction
  - [ ] Update SDE Prod
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Create ADO Issue (?)
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
</details>

----

## Footnotes
<b id="f1">1:</b> If EARD provides designations for month. [↩](#a1)

<b id="f2">2:</b> If MIH issued by City Council for month. [↩](#a2)

<b id="f3">3:</b> If Zoning District changes in SI/BX10 for month. [↩](#a3)

**\*** clicking icons will navigate user back to original line of footnote

**Comment by jackrosacker** [comment]
Error in Sidewalk Cafe tool:
```
********************* Raster processing *************************
Creating File GDB
Copying Scanned Geo Maps to FGDB
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\NYC_Zoning_Maps
********************* Completed Raster processing *********************
********************* Updating Metadata *********************
******* flist: 
[u'C:\\temp\\zoning\\20230906\\fgdb\\georeferencednyczoningmaps.gdb\\georeferencednyczoningmaps']
*****infile name::::::::::**********
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Updating metadata for C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps

template processing name is M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\Metadata\zoning\AGS10\georeferencednyczoningmaps.shp.xml
Traceback (innermost last):
  File "M:\GIS\BytesProduction\PyProcessing\TRD\Scripts\ZoningDistrictsWeb_tool.py", line 795, in <module>
    UpdateMetadata(rasIndex, dirWEB, MetadataFolder, MetadataVersion, MetadataCalDate, MetadataPubDate, MetadataChangesDesc, CouncilDate)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\Scripts\ZoningDistrictsWeb_tool.py", line 184, in UpdateMetadata
    UPDATE.replace_values(MetadataTemplate, "#", "#", MetadataCalDate, MetadataPubDate, CouncilDate)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 229, in replace_values
    replace_councilDate(tree_dom, replacement_list, COUNCIL_DATE)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 99, in replace_councilDate
    node_value = get_node_value(node)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 32, in get_node_value
    return node[0].childNodes[0].data
 IndexError: list index out of range



Completed script SidewalkCafe...
Failed to execute (SidewalkCafe).
Failed at Wed Sep  6 14:12:42 2023 (Elapsed Time: 42 minutes 1 seconds)
```

Troubleshoot w/ @caseysmithpgh on 9/7/2023

Note also that the tool was run once, the error occurred, and an attempted fix was renaming an XML to:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXh6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ab4db248673b0c3ab192053ac544cc13ae4ff19/image.png)
The original file name was: `GeoreferencedNYCZoningMaps.shp.xml`

**Comment by croswell81** [comment]
@jackrosacker I reviewed City Map Alterations (nymi) dataset that is part of the monthly DCM release. There are changes for TRD to make so I sent them an email, instructing that the ALTMAPPDF field was updated to change any .tif/.tiff to .pdf but the URL in the Link_address field was not. That should be fixed before we pull and process. Once we get notification from TRD you can proceed with DCM processing.

Sent TRD email to update the

**Comment by jackrosacker** [comment]
Troubleshooting tool.
Found that the metadata XML template names are hardcoded into a function within the `update_metadata.py` file, that is called by the primary `ZoningDistrictsWeb_tool.py` tool script.

We replaced the `\AGS10\georeferencednyczoningmaps.shp.xml` file with the archived snapshot file with the pre-existing CamelCase spelling name, and re-ran the script. Errored again, with this slightly different error message:
```
*****infile name::::::::::**********
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Updating metadata for C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps

template processing name is M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\Metadata\zoning\AGS10\georeferencednyczoningmaps.shp.xml
Traceback (innermost last):
  File "M:\GIS\BytesProduction\PyProcessing\TRD\Scripts\ZoningDistrictsWeb_tool.py", line 795, in <module>
    UpdateMetadata(rasIndex, dirWEB, MetadataFolder, MetadataVersion, MetadataCalDate, MetadataPubDate, MetadataChangesDesc, CouncilDate)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\Scripts\ZoningDistrictsWeb_tool.py", line 184, in UpdateMetadata
    UPDATE.replace_values(MetadataTemplate, "#", "#", MetadataCalDate, MetadataPubDate, CouncilDate)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 229, in replace_values
    replace_councilDate(tree_dom, replacement_list, COUNCIL_DATE)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 99, in replace_councilDate
    node_value = get_node_value(node)
  File "M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\ApplicationCode\Python\Metadata\metadata_update_tool\update_metadata.py", line 32, in get_node_value
    return node[0].childNodes[0].data
 IndexError: list index out of range



Completed script SidewalkCafe...
Failed to execute (SidewalkCafe).
Failed at Thu Sep  7 11:54:03 2023 (Elapsed Time: 42 minutes 19 seconds)
```

**Comment by jackrosacker** [comment]
Sidewalk Cafe Tool is now running successfully. Latest change was ensuring that the all lowercase naming convention exists in all of the following places:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDk2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--baccfc51c975f284ca9496d305cb6a4494d5a88b/image.png)

Pasting the relevant log file lines here. Note the text stating XML template does not exist. Feels weird, but no way to compare to previous runs:
```
********************* Raster processing *************************
Creating File GDB
Copying Scanned Geo Maps to FGDB
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\NYC_Zoning_Maps
********************* Completed Raster processing *********************
********************* Updating Metadata *********************
******* flist: 
[u'C:\\temp\\zoning\\20230906\\fgdb\\georeferencednyczoningmaps.gdb\\georeferencednyczoningmaps']
*****infile name::::::::::**********
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Updating metadata for C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps

template processing name is M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\Metadata\zoning\AGS10\georeferencednyczoningmaps.shp.xml
**************replace council date RASTER ******************
here
2/28/2023
8/31/2023
here
2/28/2023
8/31/2023
here
The date of the most recent City Council adoptions included in this data is 2/2/2023.
The date of the most recent City Council adoptions included in this data is 8/3/2023.
C:\temp\zoning\20230906\web\metadata_GP
Removing unnecessary metadata info..............
-------------- Begin XSLT Transformation ---------------
Completed xml coversion on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Imported XML on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
-------------- Begin XSLT Transformation ---------------
Completed xml coversion on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Imported XML on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
-------------- Begin XSLT Transformation ---------------
Completed xml coversion on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Imported XML on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
-------------- Begin XSLT Transformation ---------------
Completed xml coversion on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Imported XML on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
-------------- Begin XSLT Transformation ---------------
Completed xml coversion on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
Imported XML on C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps
C:\temp\zoning\20230906\web\georeferencednyczoningmaps_metadata.html
Executing: XSLTransform C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\georeferencednyczoningmaps "c:\program files (x86)\ArcGIS\desktop10.8\Metadata/Stylesheets/ArcGIS.xsl" C:\temp\zoning\20230906\web\georeferencednyczoningmaps_metadata.html #
Start Time: Thu Sep  7 13:20:46 2023
Succeeded at Thu Sep  7 13:20:48 2023 (Elapsed Time: 1.26 seconds)
removing No thumbnail tag
removing fdgc tag
removing h2 fdgc tag
completed
M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\Metadata\zoning\AGS10\georeferencednyczoningmaps.shp.xml does not exists.
********************* Zipping Raster FGDB *************************
C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb
C:\temp\zoning\20230906\web\georeferencedzoningmaps_202308.zip
...
...multiple lines removed for legibility...
...multiple lines removed for legibility...
...
Zipping: C:\temp\zoning\20230906\fgdb\georeferencednyczoningmaps.gdb\timestamps
********************* Completed Zipping Raster FGDB *************************
Minutes: 130.414880608

Zoning Districts: End processing
Completed script SidewalkCafe...
Succeeded at Thu Sep  7 13:22:10 2023 (Elapsed Time: 44 minutes 23 seconds)

```

**Comment by jackrosacker** [comment]
Weird - output raster metadata seems to be fine, but the tool message states that the XML was not found, and it looks like the name of the template XML was reverted back to the CamelCase spelling convention during the tool run:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakY4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40a89f191272ba83814f4d057fe63fae6bfb774a/image.png)


To test again - I just reverted the name of the template file back to all underscores, and added an extra print statement to the end of the relevant function in update_metadata.py to print the name of the XML to see if it is being renamed mid process: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalI4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49492b087dcf879b843dc9a941be1f75dba902b7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak44IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49d86fd131679bdff15f097ca33a60d310454fe8/image.png)

**Comment by jackrosacker** [comment]
Sidewalk Cafe tool ran successfully. XML template was set to underscores before running, and remained as such after the tool had finished. The trick appeared to be changing the hardcoded template name in the `update_metadata.py` file.
Curious print statement remains, but doesn't seem to be impacting outputs - both data and metadata appear fine.
```M:\GIS\BytesProduction\PyProcessing\TRD\ArcGIS_Team_Files\Metadata\zoning\AGS10\georeferencednyczoningmaps.shp.xml does not exists.```

**Comment by jackrosacker** [comment]
Error in zoning data reported by member of public. Requires re-publish of Zoning + ZTLDB products using current data.

**Comment by jackrosacker** [comment]
Publish to AGO process failing for Zoning and DCM data. Same error message appearing for both products:
```
found Service Definition : 435fdd736a0c409cb7ce399fc020064c
mappingMXD.tags: Toll Crossing, New York City City Map, Department of City Planning, Arterials, Principal Routes, Master Plan Map, City Map, Major Streets, Archive, Parkways
IOError on save, do you have the MXD open? Summary/tag info not pushed to MXD, publishing may fail.
Traceback (most recent call last):
  File "//120bfs01/vol2/DIVISION/GISTEAM/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py", line 85, in <module>
    execfile(updatePy)
  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 502, in <module>
    makeSD(MXD, serviceName, tempDir, finalSD, maxRecords, tags, summary)
  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 435, in makeSD
    arcpy.StageService_server(newSDdraft, outputSD)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.8\ArcPy\arcpy\server.py", line 1411, in StageService
    raise e
arcgisscripting.ExecuteError: ERROR 999999: Error executing function.
Failed to execute (StageService).
```

**Comment by jackrosacker** [comment]
DCM and Zoning publication to AGO completed manually.

The following products have been migrated to new issues:
WPAA to [Waterfront Property Access Areas (WPAA) #988](https://github.com/NYCPlanning/edm-overview/issues/988)
Housing to [September 2023 Open Data updates #986](https://github.com/NYCPlanning/edm-overview/issues/986)
MapPLUTO to likely a sprint in October
